### ISSUE TITLE
problem with the film cover

### ISSUE THREAD

**Issue by tiagomiguel1994** [123Venom/plugin.video.venom#108]
Good afternoon, first of all I want to thank the developer of this addon because it's extraordinary.  
I have a small problem with the covers of the films, they are not the main ones in the film, I was looking at other addons and they all have the original covers, I already did a hard reset on Kodi I installed everything again and the covers are not the same I already installed the api on fanart.tv in addon and tmdb and nothing happens... 
And some covers are not loading...
I'll send a photo for you to see.  
Thank you very much

Image 1 the covers do not load
![20210801_170353](https://user-images.githubusercontent.com/88282663/127777736-f0c6a156-dd77-4513-839a-1130fcc04fb2.jpg)

image 2 and 3 the different covers on Venom
![20210801_170444](https://user-images.githubusercontent.com/88282663/127777801-c01ffc8a-09a2-449b-938f-1d03ebd7f6e3.jpg)
![20210801_170459](https://user-images.githubusercontent.com/88282663/127777805-6f985a56-da79-4a33-b830-ec269fe730df.jpg)

image 4 and 5 the original covers in other plugins
![20210801_170548](https://user-images.githubusercontent.com/88282663/127777859-d8f11a8d-9acd-497f-a415-ed9a808a4580.jpg)
![20210801_170532](https://user-images.githubusercontent.com/88282663/127777864-c28c1b77-1c0e-4f2c-ae2b-a892279e128a.jpg)

**Comment by drinfernoo** [comment]
Different add-ons use different posters sometimes. It depends on if they get them from TMDb or Fanart.tv, usually.

**Comment by tiagomiguel1994** [comment]
Yes, but about 2 months ago Venom had the original covers but I did a cache cleanup and that's when it started to download these covers. Is there any option to choose between fanart.tv and tmdb?

**Comment by 123Venom** [comment]
I'm a little confused with pic1 and pic2.  The posters were not there at first then were?  As far as what poster is chosen works like this....If you enable fanart.tv that becomes the preferred artwork.  Artwork from fanart.tv is pulled based on the most liked first.

[The Tomorrow War](https://fanart.tv/movie/588228/the-tomorrow-war/)

As you can see the keyart version of that poster is first in the most liked so it's priority.  The reason it changes is because at one point another poster had a higher like count so it can change from time to time...that was my intent to have the most popular.

Someone just yesterday asked me if I could make TMDb poster and fanart have priority.  I'm considering adding a setting for this.

**Comment by tiagomiguel1994** [comment]
Yes, the first time it wasn't there but then I turned the page back and forth and then the cover was downloaded.  This has happened to me a few times already.
So what if I have another option besides fanart.tv?  
Yes I had already noticed that the cover was the one that had the most likes first.  
Ok if you could add this function it would be cool... 
There is 1 addon that works very well with the covers, is just change the API language for example to portuguese, and the cover are automatically changed to portuguese.
By the way, is there a platform where I can contribute to this project?  Because I'm aware of the work this gives and how good this addon is...

**Comment by 123Venom** [comment]
I asked about that pic1 vs. pic2 because it struck me odd and I've never witnessed that. Could be a service causing a momentary lag loading those.

Next release I'll have a new setting so you can set your preferred provider for poster and fanart.

No contribution necessary.
