### ISSUE TITLE
Library playback still not working

### ISSUE THREAD

**Issue by TheGuru276** [123Venom/plugin.video.venom#111]
As of v6.1.3 I still haven't been able to restore library playback functionality.

I went back to v6.0.8 and playback instantly restored.

What is this country code check and what do I need to fix or amend?
[kodi-venomplaybackerr.log](https://github.com/123Venom/plugin.video.venom/files/6948800/kodi-venomplaybackerr.log)
[venom-playbackerr.log](https://github.com/123Venom/plugin.video.venom/files/6948803/venom-playbackerr.log)

**Comment by TheGuru276** [comment]
I think some of the issue might be evident in the venom log.  It references The Gunrunner Billy Kane But that's not the show/episode title I was trying to watch. I was trying an episode of Blindspot called Senile Lines S02E18

https://www.reddit.com/r/Addons4Kodi/comments/oz58ie/venom_playback_fails_for_everything/?utm_medium=android_app&utm_source=share

**Comment by 123Venom** [comment]
The country code check is because there are titles out there that like to put the country code into the magnet `release_title`.  The case we found was `Animal Kingdom`  here's an example...
```
Animal.Kingdom.US.S01.1080p.BluRay.x264[rartv]
```
Having the country code immediately follow the show title would cause our aggressive title checking to fail and the links would not be included as a match.  It also now picks up a few stragglers here and there as uploaders are incorrectly adding this country code to titles when they should not be. **Yellowstone** and **The Witcher** I recall off top of my head were titles extra links were pulled with this new country code added and there was more.  I doubt this is your issue as that just required me to use the `country_code` returned from TMDb api response that previously I had no need for and did not use it.

Looks like no trakt account per log and this is a current known issue atm that I do have fixed, but it does not seem to be your failed playback issue.  There's also some failed to mark as watched issues currently we're resolving when no Trakt account.  It's a different matter but related to your issue post and thought I would mention it. I'll be working with Eldorado this coming week for an update to **metahandlers** in hopes to resolve the marking issues not working for non Trakt account users.

```
msg : tvshowtitle: (The Gunrunner Billy Kane) missing tmdb_id
```
Seeing this in the log is not harmful in the least.  This is just me logging failed titles to which TMDb does not have so I can report them if desired.  I'm assuming this title is not in your local library because I could not pull that title from TMDb, TVDb, or Trakt.  Seems IMDb is the only one with this title.

I then added the **Blindspot** to my own library and S02E18 scraped and played fine.  Does the source select screen come up, or are you on AutoPlay?

Your log implies this is a broken meta condition that I'm not sure just yet what might be breaking it.  These are the lines that's causing the failure.
```
[2021-08-04 09:10:06] [COLOR red][ Venom: ERROR ][/COLOR]: From func name: /resources/lib/modules/sources.py.checkLibMeta() Line # :215
                       msg : KeyError -> 'imdb'
```
```
[2021-08-04 09:10:08] [COLOR red][ Venom: ERROR ][/COLOR]: From func name: /resources/lib/modules/sources.py.playItem() Line # :272
                       msg : Error playItem:  -> TypeError -> argument of type 'NoneType' is not iterable
```
The first I'm trying to match the imdb id, that should get passed from the .strm file, to the records in the Kodi database for your library items.  That causes the meta pull failure resulting in the 2nd line error.
what gets me on that `imdb` error is it's right in the path passed as expected here, and is fine for me.
```
path [plugin://plugin.video.venom/?action=play&title=Senile+Lines&year=2015&imdb=tt4474344&tmdb=62710&tvdb=295647&season=2&episode=18&tvshowtitle=Blindspot&premiered=2017-04-05]
```

What library scraper are you using for shows?
Do you have TMDB Helper installed, with it's contenxt menu addon? If so can you test using the CM option `TMDbHelper Options` and that'll let you pick one of the Venom players.  That also worked for me but I want to see how it behaves your end.

Not able to duplicate this issue here atm.  I'm going to keep digging about and see if I can spot any reason why that `imdb` id is getting hosed.  I even revoked my own Trakt account, cleared all cache and metacache and yet it still works fine.

**Comment by 123Venom** [comment]
Ahh this big dummy was not paying attention.

```
[2021-08-04 09:10:06] [COLOR red][ Venom: ERROR ][/COLOR]: From func name: /resources/lib/modules/sources.py.checkLibMeta() Line # :215
msg : KeyError -> 'imdb'
```
This error is saying the the dict key I'm trying to obtain from the Kodi library is the issue.  Few versions ago I was getting reports that random shows failed and it was due to the method I search for the matching title in the Kodi database.
```
meta = [i for i in meta if str(i['year']) in years and (t == cleantitle.get(i['title'].replace('&', 'and')) or t == cleantitle.get(i['originaltitle'].replace('&', 'and')))]
```
Above was the old method which searches for a cleantitle match and year match+/- 1. cleantitle was causing issues

I'd have to look but I think v6.1.0 I switched to this
```
meta = [i for i in meta if i['uniqueid']['imdb'] == self.imdb]
```
My opinion was an imdb id match should be dead on and any odd characters in the title should no longer cause an issue with this method.  I know the tmdb scraper sets the `uniqueid` in the kodi library but perhaps you are using the tvdb scraper and it's not setting those ids?  I'll try switching scrapers and see what the scraper is writing to the database but I think we're getting close.

**Comment by 123Venom** [comment]
Switched to tvdb scraper and that's not it.  The scraper writes the ids to the kodi database just fine and also pulled out for me without your log error.  Scrape to play went fine as well.

```uniqueid=[{'imdb': 'tt4474344', 'tvdb': '295647'}]```

**Comment by TheGuru276** [comment]
I have been using tmdb TV shows information scraper for most of the time but I found it getting slower and taking too long as my library grew in size so around the time that library playback started playing up for me I also switched to the movie database scraper. But after a few days of library playback still not working I switched back to tmdb TV shows.

You are correct I don't use Trakt at this stage but have been considering it and the gun runner Billy Kane title is not in my library. I'm using all debrid rather than real debrid in case that wasn't obvious but I wouldn't think that would be a factor in what's going on.

I use the source select-xml window in your addon rather than autoplay and yes I am also have TMDBHelper. If I use it's content menu on my library and select the Venom source select player it still fails to play but will obviously play if I choose any other addons player.

**Comment by TheGuru276** [comment]
Here is my Venom settings file if that helps with your troubleshooting
[venomsettings.zip](https://github.com/123Venom/plugin.video.venom/files/6950089/venomsettings.zip)

**Comment by TheGuru276** [comment]
[blindspot library files.zip](https://github.com/123Venom/plugin.video.venom/files/6950118/blindspot.library.files.zip)

**Comment by 123Venom** [comment]
I finally just duplicated your issue.  Since I jumped the gun and changed my scraper to TVDb to test I now just switched back.  Upon the library re-scraping the items it became apparent something went terribly wrong and I'm looking at db corruption.
<img width="928" alt="13b" src="https://user-images.githubusercontent.com/46383815/128618421-9c3868c6-ecf1-464c-a983-1bcbc094ee13.PNG">

Then low and behold I now get the same error as you when I tried to play that episode.
```
[2021-08-07 21:31:04] [COLOR red][ Venom: ERROR ][/COLOR]: From func name: \resources\lib\modules\sources.py.checkLibMeta() Line # :225
msg : KeyError -> 'imdb'
[2021-08-07 21:33:48] [COLOR red][ Venom: ERROR ][/COLOR]: From func name: \resources\lib\modules\sources.py.playItem() Line # :282
msg : Error playItem:  -> TypeError -> argument of type 'NoneType' is not iterable
```
Then the source select screen found no cached torrents and the meta is a mess
<img width="1356" alt="13a" src="https://user-images.githubusercontent.com/46383815/128618442-8c21a993-223b-4c78-a36b-43cfcfa27788.PNG">

Since you just mentioned you switched scrapers and back again...that's exactly what just triggered this to me.  It worked fine till I flipped them back and forth.  Do you see any goofy items in your library, like my first pic, that might indicate a corrupt database?
Now that I had data that throws this error I altered that new line looking for the imdb id and fixed it even with this corruption shit going on.  However, I need to try and rebuild the db because that's down right nasty what it did..lol

how handy are you at editing a file?  It's one line I could give you and tell you what to replace.  Just as a quick test but it fixed playback for this hot mess issue that appears to be a corrupt db.

Should be able to get a fix out for this next release.

**Comment by 123Venom** [comment]
ohh btw..AD is down at the moment to.  I have AD, PM, RD, and EasyNews.  That's one reason no AD links are returning at the moment and the log will indicate the server timeouts going on with them right now.

**Comment by 123Venom** [comment]
Those goofy folders in my pic, that's what caused the break for me because it didn't return a `uniqueid` key with `imdb` in it and breaks the whole library scan Venom does.  I just now manually removed the items, cleaning alone won't fix it.  Then I did an **Update library** and the database key is back to being intact.  My guess is one of you library items is corrupt from the flip you once did, and it did the same thing to me.  The code line I spoke of will fix the condition if that key is kaput due to corruption or missing and let Venom continue to scan library content now, but it will ignore the encountered problem item though.

**Comment by TheGuru276** [comment]
Ah first AD outage for me since switching from RD 4 months ago. Because I was just about to add an extra comment letting you know that my AD cloud sources are no longer showing up in the results.

By goofy items do you mean TV shows with just the white folder icons? I've had a little bit of that in my library for a while which I put down to it not liking duplicates or accidentally still having the don't allow duplicates setting enabled within the addon when I have some episodes saved locally. In that scenario I seem to lose the network icon and is replaced with a white folder.

**Comment by 123Venom** [comment]
YEP..that white folder icon you see...THAT'S LIBRARY CORRUPTION.  Occurs for some odd reason flipping scrapers.  If you fix that now per what I outline then it should be fine and the fix I push to puclic will take care of any future library problem should it happen again.  OK here's what you need to do.  Make sure in Kodi **system settings** - **Media** - **General** make sure both **Show hidden files and directories** and **Allow file renaming and deletion** are turned on.  Now go up one category from **General** to **Library** and perform a **Clean library**.  Now go back to your TV Shows library and those ugly ass white folders you want to bring up **context menu** then **Manage**.  Now select **Remove from library**.  Answer yes to first prompt.  Answer NO to second prompt.  The second prompt will ask about deleting the .strm, do not delete that....although if Venom were to scan new content it should put it back if you gaff one.  Once those are removed your database should now not contain any of these missing `imdb` keys that is breaking it

**Comment by 123Venom** [comment]
if you want to toss up a screenshot of your folder cases I might be able to spot if it's a hosed library item or not.  If it appears as some sort of season/episode then my guess is it's corruption.  I just know I never had that crap before but when I flipped scrapers back and forth these new goofy folders showed up that were never there, and they thru this missing `uniqueid` with no `imdb` id error so it was data corruption imo.  Once I cleaned the cases per my outline above the error was gone.
<img width="1310" alt="19d" src="https://user-images.githubusercontent.com/46383815/128619209-4ffceaa7-ac98-462d-a577-79377c25ca04.PNG">

**Comment by TheGuru276** [comment]
Ok thanks. Just an FYI only 1 show with a white folder was added to the library using Venom and added recently, Sexy Beasts from Netflix, the other five shows were all added months/years ago from the Oath

**Comment by 123Venom** [comment]
I'm guessing your **Sexy Beasts** with the white folder is what is breaking it and when things went south.  Try deleting it.  I've never seen Venom add an item to library and ended up with a white folder.  Do seasons and episodes load fine for that item?

**Comment by TheGuru276** [comment]
Yes, we've even watched the first 2 episodes successfully

**Comment by TheGuru276** [comment]
Already jumped in and removed the 5 affecting TV shows but I had nothing like your screenshot of weird season folders or wrongly named shows, everything was correct and listed fine, just with white folders on 5 shows

**Comment by TheGuru276** [comment]
Thank you for your time and effort and being so responsive given that this might only affect a small number of users it is greatly appreciated as I prefer your add-on above all others

**Comment by 123Venom** [comment]
I added it.  It made a liar out of me...lol

<img width="1345" alt="19e" src="https://user-images.githubusercontent.com/46383815/128619308-cb25b8c2-ab8e-4330-8308-50b148963d1e.PNG">

But it made me curious if this sucker is causing issues with this `uniqueid` key in database.  Nope..log says it's solid
```
'uniqueid': {'imdb': 'tt4015496', 'tmdb': '62217', 'tvdb': '284123'}
```

ids are all there and the library scan completed and playback was fine.  I'm pretty damn sure there's an item in your library that is corrupt and missing this key that breaks the scan process Venom is trying to do.

You want to try editing a line of code?

**Comment by TheGuru276** [comment]
Sure, I competent enough to modify stuff

**Comment by TheGuru276** [comment]
By the way my library listing is full of TV shows with no network icon at all, just blank,  and I don't think I've got any that has the Netflix icon which I just assumed might have been some sort of licensing issue that Netflix would have Sued the ass out of anyone using they're icon

**Comment by 123Venom** [comment]
ahh.  Ya know why it's a folder icon?  Because there's only one season so when I select that show instead of seeing a season folder...I see the folder at the show level.  I think there's a setting to not do that but it's not a Venom thing anyway because if you look in the userdata folder that show has a season folder...it's just ignored by either Kodi library.

ok, code change.  You can find the **plugin.video.venom** folder right?  You want the sub-folder called **modules**.  In that folder you want the file named **sources.py**.  Do you have notepad++ by chance?

**Comment by 123Venom** [comment]
In that file look for the first line I show below.  It happens in 2 places, one for movies and one for episode playback.  You're adding the second line.  The `#` is to basically comment out the first line so I'm just shutting it off so the second line gets used in it's place.  This also happens again in the play.py module but that's just for extended artwork and won't hurt anything staying as is for this test.  Then we'll know if this gets it's playing

```# show_meta = [i for i in show_meta if i['uniqueid']['imdb'] == self.imdb]```
```show_meta = [i for i in show_meta if i.get('uniqueid', []).get('imdb', '') == self.imdb]```

**Comment by TheGuru276** [comment]
I've used it in the past, will just need to install it on my current working computer.

BTW after removing the 5 affected shows and doing a library update I have a lot more network icons in my library including the Netflix ones but one of the 5 affected shows has returned with a white folder. Travel Guides AU, which I only have local content for, nothing from an addon and I've always had trouble getting the scrapers to identify that show as it's one of those ones that are duplicated in many countries like big Brother and The amazing race etcetera

**Comment by 123Venom** [comment]
ohh be careful...movies is slightly different

```# meta = [i for i in meta if i['uniqueid']['imdb'] == self.imdb]```
```meta = [i for i in meta if i.get('uniqueid', []).get('imdb', '') == self.imdb]```

You'll spot it

**Comment by 123Venom** [comment]
I'll check that show while you do your notepadd++ adventure

**Comment by 123Venom** [comment]
yep, it gave me a folder icon as well for that show yet it has four seasons.  Frankly I have no idea why it's using a folder icon.  Sometimes the studio icon is shown for me and other times is just blank.  Now I get a few with a folder icon..lol.  As long as it looks to be intact data wise that's more concerning to me.  The cases in my pic were it was all messed up was me seeing season and episode folder info when I know the local stored content is not that structure, that told me there's corruption of some sort had taken place and playback even failed.

**Comment by 123Venom** [comment]
Should look like this for movies.  If your line numbers do not exactly match do not be alrmed.  I have some other changes that are not in the public release yet.
<img width="609" alt="movies" src="https://user-images.githubusercontent.com/46383815/128619884-19cb0855-711a-41bc-a3a5-156095307abf.PNG">

Episodes should look like this.
<img width="665" alt="episodes" src="https://user-images.githubusercontent.com/46383815/128619902-b7684a47-3bcf-43e0-a769-edd9f5562868.PNG">

**Comment by TheGuru276** [comment]
all edited, just uploading it back now

**Comment by 123Venom** [comment]
cool

**Comment by TheGuru276** [comment]
Was going to so Ill try it before committing the modification', oh but I only have AD so probably cant do any testing ATM

**Comment by 123Venom** [comment]
yep, I forgot AD down atm

**Comment by 123Venom** [comment]
other than tonight's BS with AD I really like them.  Their api is so nice to work with.  RD I can't stand, their api sucks to.

**Comment by TheGuru276** [comment]
I was having to reauthorise RD probably twice a week in the add-ons. I eventually got sick of it and two weeks prior to my subscription expiring I decided to test AD as Reddit was getting quite a lot of posts at the time about people struggling to renew with RD. I'm glad the timing worked out well for me because about 2 weeks later they started having all of those major frequent outages

**Comment by TheGuru276** [comment]
Which scraper do you suggest I stick with?

**Comment by 123Venom** [comment]
Scraper as in library scraper?  The TMDb TV Shows imo is the best one. Handles fetching fanart.tv extended artwork itself.

If not for support of it I'd toss RD out the window myself.  I ever quit development RD prob first to go.

**Comment by TheGuru276** [comment]
And while I have you, rumour has it that you might be dropping library integration at some point. if so is there some other way I should be using Kodi? Is it time I finally used Trakt as the main thing holding me back is the frequency of Reddit posts with issues with Trakt and one other particular addon that everyone seems obsessed with so I've had little interest in using either

**Comment by 123Venom** [comment]
Ya I have been talking among some people about wanting to rid library integration.  It can be very frustrating at times and I honestly do not use it for everyday use.  I just keep a library for testing for you all...lol. I also have developed a real bad habbit when I add new features I forget to consider it's impact on library integration and low and behold I break it.  That's happened at least a dozen time this year alone.  When Fen removed library integration allot of people went with TMDb Helper so that's an option.  I don't think I'll remove it any time soon.  It's probably going to come down when an issue beats the tar out of me so bad one night I throw a tantrum and remove it...lol

What I'd do if I were you is get a Trakt Account.  Your missing out on quite a bit without one.  Yes it goes down like anything else and they all have their maintenance time, but I couldn't live without Trakt myself.  I use the Trakt Progress as a home screen widget so all my episodes NextUp to watch are right there.  I had made an `UpComing Episodes` list so I could also monitor when my shows will be coming back on so I can see those future air dates.

**Comment by TheGuru276** [comment]
While I work out what I do next then I hope this issue hasn't pushed you over the edge. 😂

**Comment by 123Venom** [comment]
naaa, I think we got it.  It's the ones that carry on for days and me spending hours code hunting.  This was nothing.  It's a good thing I tested flipping library scraper cause I'd still be scratching my head. That flip made it show it's ugly ass right away.

**Comment by TheGuru276** [comment]
Ok. AD is back up and tried it without the modified sources file and I still didn't see my AD cloud file but got other AD links that still wouldn't play.

Want me to go ahead and test the modified file?

**Comment by 123Venom** [comment]
yes go ahead test it

**Comment by TheGuru276** [comment]
Ok, so I've been testing it mostly with a few of the Season 2 Blindspot episodes which have continue to fail so I decided to try it with the latest season of animal kingdom as I haven't watched any of it yet before I use the modified file and it played OK

**Comment by TheGuru276** [comment]
Season 1 of Ted lasso is another show I've used for testing and my AD cloud source showed up but wouldn't play

**Comment by 123Venom** [comment]
Not sure why it's failing for the Blindspot still.  I just uploaded a zip to my `zips` folder in the dev branch.  it's v6.1.3.5.  That has a few other thing but I carried this change thru into the player where i told you the issue also exists but that really only effected artwork.  I was not to concerned with artwork.  Try that.  Just kind in mind under 19 when you install from zip auto updates stop happening so when i do push a new official version you'll get the notification it's available, if it's on, and then you'd have to install the new version from repo.

**Comment by 123Venom** [comment]
still something screwy going on and I'm wondering if that Show itself doesn't have something corrupt in your library.  If that zip still won't play those episodes for that show I'd try removing that show, and it's `.strm` files, so you'd be saying `yes` to that second prompt.  Then add it back to the library and ssee if the problem still exists.

**Comment by 123Venom** [comment]
also check the venom.log....if still failed playback toss it on here

**Comment by 123Venom** [comment]
> 
> 
> Season 1 of Ted lasso is another show I've used for testing and my AD cloud source showed up but wouldn't play

If you go to this show inside Venom does this cloud source play there?  Total shot in the dark but we've come across some shows that are `.m2ts` and movies are easy to resolve and play as it's just simply getting the largest video file....but..shows are impossible.  each episode is just some number like `00028.m2ts` and we have no way to know what episode in the lot that is.  We don't support `.m2ts` playback of episodes.  So what I'd ask you to do is log onto your AD account and find that item.  Then click `show links` and give me a screen shot like this.

<img width="724" alt="ad" src="https://user-images.githubusercontent.com/46383815/128626126-39035ef2-ea00-4318-bcc6-c8f5345b9c79.PNG">

That's an `.m2ts` but since it's a movie AD nicely picked the largest video file for us.  Episodes are a whole different ballgame.  I doubt yours is an `.m2ts` as they are a little rare.

**Comment by TheGuru276** [comment]
I don't have good news. The modified sources file caused an error as I tried to scrape for sources.

I've attached the Venom log and the sources file so that you can check that I modified it correctly.

The first half of the Venom log is testing after we removed what we thought were corrupted TV shows before modifying the file where blindspot and Ted lasso fails but animal kingdom is successful the second half of the Venom log is with the modified sources file that errored during the scrape for sources.

Where do I get the 6.1.3.5 zip file from?
[testing.zip](https://github.com/123Venom/plugin.video.venom/files/6950478/testing.zip)

**Comment by TheGuru276** [comment]
I found the zip file. I'll try 6.1.3.5 now

**Comment by 123Venom** [comment]
ya you got a mix of tabs and whitespace.  Ironically when you restarted the `imdb` error went away so this seems to be a rare case that Kodi wasn't tweaking over over the mix of tabs and whitespace, as a rule I just never do that.

The zip is on here.  Go to the repositories and open the zips folder....then select the dev branch and you'll see it.  Looks like this
<img width="696" alt="dev" src="https://user-images.githubusercontent.com/46383815/128627718-e7b501bf-5c85-4de0-8193-750f4784cb98.PNG">

Also do a library clean to.

**Comment by TheGuru276** [comment]
6.1.3.5 works

**Comment by 123Venom** [comment]
I just tried your file.....yep Kodi is tweakin out real bad with errors over tha mix of tabs and whitespace

**Comment by 123Venom** [comment]
> 
> 
> 6.1.3.5 works

Nice.  Think what you had would of done the trick if you used tabs and lined it up.  Check that **Ted lasso** and get me that snip

**Comment by TheGuru276** [comment]
Oh. All I did was open it in notepad++ click the mouse where I needed to make the change and paste then click back up on the line above to add the #

**Comment by 123Venom** [comment]
I had like 97 links for S01E01 and I got down into the 40's and every AD link played for me.  I need to see what link failed for you.

**Comment by 123Venom** [comment]
> 
> 
> Oh. All I did was open it in notepad++ click the mouse where I needed to make the change and paste then click back up on the line above to add the #

prob didn't have symbols turned on so you could see my code uses tabs and default prob used whitespace on you
<img width="645" alt="19a" src="https://user-images.githubusercontent.com/46383815/128628017-1a03ec36-a85f-4bef-a535-7be29568be69.PNG">

**Comment by TheGuru276** [comment]
![Screenshot 2021-08-08 19 53 13](https://user-images.githubusercontent.com/88575969/128628043-1a9f6203-716f-4b56-a701-913fe3ce3d09.png)

**Comment by 123Venom** [comment]
This guy right here.  Played like a trooper for me.  What episode though as maybe there is something weird with one of the files inside.  I only played E01

<img width="966" alt="19b" src="https://user-images.githubusercontent.com/46383815/128628125-11c29fee-a8ae-4aa4-ba33-c9cb3be267e7.PNG">

**Comment by TheGuru276** [comment]
Last ep of Season 1 - The hope that kills you

**Comment by 123Venom** [comment]
Also you can pull up the `Browse Debrid Pack` from context menu so you can peak inside the pack file and see what's in it.  I do that at times when something doesn't play and find out the fool that uploaded it made a season pack and it's incomplete and missing episodes.  Nothing I can do about that case but we try to filter out the known offenders doing that crap.

**Comment by 123Venom** [comment]
S01E10 played fine for me in that same pack file

**Comment by 123Venom** [comment]
Bring up that Browse Pack file....will it play from that?

**Comment by TheGuru276** [comment]
Yes I've got 'Season Packs' of older shows with missing eps

**Comment by 123Venom** [comment]
> 
> 
> Yes I've got 'Season Packs' of older shows with missing eps

That's the result of the people uploading it.  We got a running list of groups that are offenders of it and we filter them out.  Still we get them.  If you stumble on a case you should screen shot the link so I can see if their a group name tied to it

**Comment by TheGuru276** [comment]
Oh It works now with 6.1.3.5, sorry the issue of it still not playing even though it showed up in the sources list was back just after the library clean out before trying my botched modification.

**Comment by 123Venom** [comment]
That episode 10 played for me straight from selecting the link and I just opened the Debrid Pack and selected that S01E10 and yet again it played

**Comment by 123Venom** [comment]
> 
> 
> Oh It works now with 6.1.3.5, sorry the issue of it still not playing even though it showed up in the sources list was back just after the library clean out before trying my botched modification.

ok so it does play now on 6.1.3.5..nice ...now I'm off to bed

**Comment by TheGuru276** [comment]
Thank you sooo much

**Comment by 123Venom** [comment]
Np.  Since your good I might not push till later in the week.  I'm getting together with Eldorado this week to resolve some metahandler issues and it'd be nice to see that update included. There was another user I guess bit with this issue maybe you can point him here
