### ISSUE TITLE
Sort error

### ISSUE THREAD

**Issue by djdirty60** [123Venom/plugin.video.venom#113]
Hello, 

There is an error in sorting watchlist.... if I put it by premiere date, everything is still mixed up.  

thanks in advance

**Comment by 123Venom** [comment]
Unfortunately the new traktsync I elected to do a minimal request to avoid bogging down the service.  The request only contains `year` and not the full `release_date`.  It should be sorting by year fine, it is here.  However the months are off and I knew that going in.  Let me know if that is what you are seeing that it's only off in the months.  I'm considering adding `extended=full` to the trakt request but more so because sort by `rating` and `votes` is now not possible but it will also better sort by `premiered` because I'll have the month/day of release also.  The draw back is added overhead which tends to slow things down the more we add and that's not good either so it tends to be a trade off of sorts.  Granted this is a background service but it's not good if an addon hogs to much service time and is why I tried to keep it to a minimal I could get away with.

**Comment by 123Venom** [comment]
I see the issue.  The new code for paginating collections and watchlist I neglected to set the watchlist sorting to follow the right setting so as is it's following `movies` or `shows` currently as the default sort method.  I'll fix that.
