### ISSUE TITLE
Watchlist refresh

### ISSUE THREAD

**Issue by naudski** [123Venom/plugin.video.venom#115]
Hi!

Whenever I add a movie to my watchlist using for instance Wako, my Watchlist is not updated in Venom. The watchlist in all my other addons (like FEN and Seren) are updated instantly. 
I'm using v6.1.7 and I saw something about a fix regarding sync Trakt watchlist but it doesn't seem to work.

**Comment by 123Venom** [comment]
There are two problems going on here.  First one I just discovered I used the wrong Trakt activities check in the sync process to detect a new item has been added to your **Watchlist**.

Currently using:
```
watchListActivity = getWatchedActivity()
```
Should have been:
```
watchListActivity = getWatchListedActivity()
```
Once I fix the above it will improve but will still not make the changes instant.  The second part of this is a bit more involved.  Due to the new traktsync methods that service runs on a clock every 15mins and checks for trakt activity changes and will re-sync new data when trakt reports said changes.  When you enter your **Watchlist** menu I do make make a single url request but instead pull this sync data from the local **traktsync.db** and it is considerably faster in doing so...but with a drawback that changes from an external source are not instant.  The only way to make them instant is to revert all traktsync changes and return to the old method, which atm I'm not willing to do.  The old method made a url request to trakt activities and fetched new data at the moment you selected to view your **Watchlist** but those 2 requests adds time in doing so vs. the sync method.

**Comment by naudski** [comment]
Thank you very much for making that clear!
And many thanks for all your effort in developing this great addon!

**Comment by 123Venom** [comment]
The next release I've added the ability to **Force Trakt Sync to local database**.  This will allow you to force the sync right away if you alter your Trakt account items and would like to not wait for the 15min service clock to refresh the data.  The option will be available in the **Trakt Management Tools**

**Comment by naudski** [comment]
Great!!!
