### ISSUE TITLE
Trakt lists created by mdblist.com show up as empty

### ISSUE THREAD

**Issue by GodsLikelyMe** [123Venom/plugin.video.venom#120]
As the title says, 2 trakt lists I created with mdblist.com show up as empty. They both show up fine in other add-ons. I tried to pull them up in movie lists and TV show lists. All other of my lists are fine. 

Venom log
https://paste.kodi.tv/ocaberuqem

Kodi log
https://paste.kodi.tv/qixavubika.kodi

**Comment by 123Venom** [comment]
bud I seriously have no idea what mblist.com is?  thought maybe imdb but ya got **list** on there to so that can't be it.  Ya got me on this one

**Comment by GodsLikelyMe** [comment]
It's a site that can automatically create trakt lists for you by entering parameters. For example

Genre - You choose what which ones you want
Year - between what years the movies were released
Excluded languages/countries - 

And a bunch more. It populates the lists and then automatically updates it by adding new ones that get released that meet your parameters. 
Here is one I made. 
https://trakt.tv/users/43v3rloco/lists/horror-2020-2021

**Comment by 123Venom** [comment]
I'll have a look and see what I can track that's causing it to break.  In the mean time the error indicates there's an issue trying to handle the results based on the Trakt header response data for **X-Sort-By** or **X-Sort-How**.  Check the lists you created and see if this mdblist.com set the default sort, maybe even try flipping the sort and back again to what it was...but none the less it appears I need to evaluate the header issue and better handle what is wrong with it in this case.

**Comment by 123Venom** [comment]
I found the issue and fixed it.  All I had to do was like your list and inside Venom it shows in the new **My Liked Lists** but would not load as you noted.  The issue was missing **release_dates** on a number of titles I did not properly anticipate and handle it so it was an easy fix once I saw what was happening.

Also on a similar note.  These **user_lists** I've been working on and the next version they will respect the pagination setting but that must happen locally for it to be accurate as Trakt request pagination doesn't work well when you can not set the desired sort and it returns by rank so it makes it useless. Local pagination will allow it to load a bit faster doing 20-40 items per page since your list is over 3k titles...huge list man!

Few things I also noted.  Fen did not load this list for me and I know the dev well so I reported it to him.  The Oath loaded it but had allot of dropped titles.

**Comment by GodsLikelyMe** [comment]
Sweet! And yea the list is pretty big and its only titles from 2020-2021. I have 1 with titles from 2010-2021 with over 9k lol 
TMDB Helper loads it pretty fast, but loads them by rank and not by date which is how I have it sorted in trakt. Seren does load it by date, but it takes forever and a day lol 

As always, you rock, dude. Thanks for looking into it.

**Comment by 123Venom** [comment]
np...I'm keeping your list in my liked list cause it's a beast with allot of nasties so it makes for a good test candidate for issues...ya got some fucked up titles in there brother..lol.  Plan is to get this version pushed tonight...you'll appreciate the new pagination of **user_lists**...it's way faster and previously I even hated using large custom lists because they were dog slow to load.  The initial still take a few secs but once the base full list is cached subsequent pages are like lightning and take about .5 secs to load on my pc.  The full list I keep cached for 48hrs so if you make changes they won't show for that duration of time unless you force clear cache in Venom where the list is held.

That issue with TMDb Helper sorting by rank is actually Trakt's default sort return from the endpoint I mentioned to you, and yes it sucks and it means jurial must not be looking at the header for **x-sort-by** that returns the users default sort method vs. the api's returned **x-applied-sort-by**, which is **rank** sorted.  The only way around it is for addons to offer local settings to resort it.  I offer those so this list if you want it local sorted, other than by rank, it follows the sort option for **Movies** so ya might want to play with that.  If you set the sort in Venom to **Default** it will use the  **x-sort-by** method and not the **x-applied-sort-by** returned by Trakt.  I gave thought to perhaps offering a new local sort setting for **user_lists** so it's independent of **Movie** sorting method but chose to hold off and see if it becomes a need.

**Comment by GodsLikelyMe** [comment]
Awesome!

If you ever wanna try my list of 9k+ titles from 2010-2021 for testing then here ya go Lol 
https://trakt.tv/users/43v3rloco/lists/horror-2010-2021

I'm a horror nut, so I wanted to get as much as possible, but that list was a bit too long, so I had made the shorter one. The cool thing about these lists is that if you check them on the trakt website, it gives you a link to them on mdblist.com , so you can customize them to your liking. 

Looking forward to the update. :)

**Comment by GodsLikelyMe** [comment]
Dude, the lists came up fast with the new update! Lol 

Awesome work!

**Comment by 123Venom** [comment]
Glad you like the update.
