### ISSUE TITLE
Finish watching keeps loading in v6.2.1

### ISSUE THREAD

**Issue by naudski** [123Venom/plugin.video.venom#123]
Hi there!
The liked lists are indeed working now but when clicking the Finish Watching section in My Movies the loading spinner keeps loading forever. The same section in My TV Shows does work however.
Clearing cache etc does not resolve this.
Issue was also present in v6.2.0

**Comment by 123Venom** [comment]
hmmm...I can not duplicate that.  How many movies in the list?  If not to many can you list them?  I may have to isolate and see if something meta wise in a specific title is causing it.

**Comment by naudski** [comment]
I think I solved it. Seems to be skin related. I use the new Cosmic skin. When I changed the skin to Artic Zephyr Resurrected and back to Cosmic again, it worked again. Weird...

**Comment by 123Venom** [comment]
Lot of weird things go on when it comes to Kodi.  Here's something to watch out for in Venom.  When you launch Venom try to never make the first thing you do is go to **Tools-Trakt Management Tools** and load any of those menus.  We've discovered if you do anything with say the Movie type menus and then attempt to go into any normal Movie list, say **IMDb's Most Popular**, you will get a busy spinner and the list will not load...try to go right back in and it does on the second attempt.  The same happens when using those Trakt Management Tools for Shows and then trying to view a normal TV Shows list afterwards.  I've had a couple devs also peak at this anomaly because the code seems fine and boils down to a bug in kodi's **reuselanguageinvoker** .  Turn that off in Venom's settings and the issue goes away.  It also throws a bogus **invalid handle** in the kodi.log with the invoker on but does not with it off.  The handle is stuck at `-1` when the invoker is on and there's no fix for this as of yet.  As long as I do not make the first thing I do is those Trakt Management Tools I won't stumble on the issue, I prefer the invoker on because it's faster.

Anyway...I still wouldn't mind seeing that log if you want to toss it up.

**Comment by naudski** [comment]
I will try to get you the venom.log asap.
Another thing I found out. I have liked lists as a widget in my skin. After the update the widgets won't load. After I re-add them as widgets they start working again. Go figure 😀
Thanks again for your work!!

**Comment by 123Venom** [comment]
The db and list creation changes I made for liked lists actually does require that and I neglected to mention that in the changelog.  You did the right thing...nice catch
