### ISSUE TITLE
[REQUEST] Get Number of Plays and Last Played Date from Trakt

### ISSUE THREAD

**Issue by Zero3ffect** [123Venom/plugin.video.venom#124]
I'm always fiddling with my Kodi skin and I thought a cool addition to it would be to show the number of plays a movie/episode has had as well as the last played date.  I looked through the Trakt API docs and it seems that this might be possible.  I assume if you can do this that you can just assign it to the default Kodi InfoLabels (ListItem.PlayCount & ListItem.LastPlayed).  Just an idea that I'm sure not many people would really care about since I doubt there are any skins that show it.  

Anyway, I want to thank for all your hard work on maintaining Venom.  It is nice to have a stable add-on that doesn't become abandoned in 6 months like pretty much every other fork has over the years.

**Comment by 123Venom** [comment]
I'll look closer at it when I get a chance.  Off the top of my head I believe this change would be significant.  The current method for retrieving ex. watched movies uses this endpoint [get-watched](https://trakt.docs.apiary.io/reference/users/watched/get-watched).  While the playcount is there all I do is iterate the response and write to database a tuple of ids ONLY for all watched movies so all I have access to at that point is ex. `[tt123456, tt98765]` in the local database.  Handling the response would have to be re-written, the database write and fetch methods would all have to be re-written.  It's interesting but sadly it'll get a very low priority due to the amount of work needed to make it possible.

Also I'm not sure I've seen a skin use `lastplayed` dates, they may and I've just not witnessed one using it.  In Venom **My Movies** and **My TV Shows** I have  **History** list where this list does indeed contain the infoLabel **lastplayed** yet Silvo uses this nowhere.  I had modified the listItem label to show this date you last watched it there next to the title.

I also poked about in Fen and Seren for the title **Jungle Cruise** since that title has been watched four times in this household and the endpoint checked out showing a **playcount : 4** but unfortunately both addons showed **playcount:1**.  I suspect nobody is actually using the official count there from Trakt.

**Comment by Zero3ffect** [comment]
It is all good.  I thought it might be something relatively simple but it definitely isn't worth the hassle if you have a rewrite a big portion of the code for it.  Thanks for taking the time to respond.

**Comment by 123Venom** [comment]
Actually I just had a chat with the Fen dev on this, as well as a user, and seems non of us are in favor of this....don't take that personal I thought it was interesting at first till i started to dig into it a bit more.  I just tested AH, AM, and Silvo.  Only Silvo shows the `playcount:?` number and you have to pull up **Information** to even see it.  None of them show the `lastplayed` infoLabel, which also sort of ruins bothering to pass this if the skins do not support it.  Was worth peaking at for sure bud you were onto something but lack of skin support would make this a no for me....lol
