### ISSUE TITLE
[Feature Request] Resume point choice

### ISSUE THREAD

**Issue by naudski** [123Venom/plugin.video.venom#129]
Hi there!
Would it be possible for you to make the option to choose between local db or Trakt scrobble as a resume point source available without having to enable the trakt scrobbling feature in Venom?

**Comment by 123Venom** [comment]
If you do not enable **Trakt Scrobble** setting then the **Resume point source**: setting is greyed out because that's all that's left and what you will get.  I don't see anything wrong with the current functionality of this setting.

**Comment by naudski** [comment]
No there is absolutely nothing wrong there, but when using the Trakt Addon with multiple addons it would be a handy feature especially when using multiple devices.

**Comment by 123Venom** [comment]
You didn't mentioned using Trakt addon.  I'd have to review my code to see if I even have it set to work with that...if so I'll change it.

**Comment by naudski** [comment]
Ah sorry for the confusion 😉
If you can make it work, that would be awesome. And if not, no harm done 😀
Thanks for your effort!

**Comment by 123Venom** [comment]
I have to review the code but thinking more on this it might be a problem.  When Venom is set for Trakt scrobble I sync the data to/from Trakt as a service so when it's needed I have it locally in a database and it's up to date and no request to the Trakt api is needed.  If I remove that ability from Venom, to rely on the Trakt addon, it would not be available to me locally and I'd have to find out if the Trakt addon keeps that local, otherwise a new request would have to be made and sadly I'm not willing to do that because it defeats the purpose of the sync service in Venom.  What is your reasoning with preferring to use the Trakt addon to do the scrobble?  If it's because of other features you can disable the Trakt addons scrobble and just use the other features of it.

**Comment by naudski** [comment]
I understand the problem. 
The reason why I wanted to use the Trakt addon is for me to be able to resume episodes and movies from different addons. Why you ask off course. I use widgets in Kodi from multiple addons and use Venom for the Finish Watching purpose among other Venom sections off course.
I use the nice discover option from Fen as a widget and when I watch a movie from that, it scrobbles to trakt. I can see this also in the Finish Watching section from Venom but I loose the resume point.
I understand if I'm overdoing it a little bit but I thought this could be easily fixed.

**Comment by 123Venom** [comment]
Venom is actually doing the exact same thing the Trakt addon is doing...making a Trakt api post of the progress for the item you watched.  That allows other addons requesting that progress from the Trakt api to fetch it.  I do not have the Trakt addon but just now I started watching the movie **Kate** in Venom.  I stopped it 10min in and a scrobble progress was sent to Trakt.  I immediately fired up Seren...the resume point was not shown but I knew it would not be because Seren's service to sync runs on a clock about every 13-15mins so the sync needs to happen first.  10mins later the resume point was now seen in Seren and worked fine.  If you watch something in Fen, and it does indeed make this scrobble post to Trakt, then any addon doing a sync of this data should be able to see it...just not immediately!!  Venom's service clock is every 15mins.  I'll check with the Fen dev as I know him well...last I knew he was not doing Trakt scrobble and that may have changed....idk.  I don't use the Trakt addon and I can see the resume point in Seren once I allow the sync service to run and vice versa Venom will see Seren's posted scrobble to Trakt once it's sync service runs.

**Comment by 123Venom** [comment]
Here's a test I want you to run since you use the Trakt addon.  Allow a resume point to be created in Fen with the Trakt addon, and I'm going on the assumption Fen does not do it's own scrobble handling and why you are using it.  Once that resume/progress point is scrobbled wait this 15min for Venom's service sync to take place..fire up Venom and let me know if the progress point is seen or not with a skin indicator of a resume point.

**Comment by 123Venom** [comment]
I did my own little reverse test of the movie **Kate**.  I started watching **Paw Patrol** in Seren...stopped at 10mins.  Seren does not notify of a scrobble sent but I'm sure it did.  It took little over 7mins but Venom sync'd this back to it's db and now shows up as a resume point in Venom.  The only reason the time frame is a bit lower there is because this just tells me if the sync occurred at 7mins in means Venom was 8mins into the service clock to perform the sync is all while Seren on the **Kate** test was 5mins in

Venom's db and it's not shown yet.

<img width="548" alt="32" src="https://user-images.githubusercontent.com/46383815/134439077-4c802185-bbea-4b7a-9187-3b6b50c9058f.PNG">


Venom's db and it now appears after 7mins

<img width="476" alt="33" src="https://user-images.githubusercontent.com/46383815/134439097-b5bd49d0-0bc8-4f78-b6ed-a47b746c99e2.PNG">

**Comment by 123Venom** [comment]
tt11832046 btw is **Paw Patrol**

**Comment by 123Venom** [comment]
I did one more test for you.  I installed the Trakt addon and allowed it to scrobble movies for this test.  Then via Fen I started the movie **The Last Mercenary** and again stopped it 10mins in.  The Trakt addon pops a notice of the scrobble so we know it takes place.  It took 13mins for it to show in Venom and again..due to the 15mins service clock so it was only 2mins into it's cycle when I started playback in Fen.

Going straight into Venom it does not show, as expected per above.

<img width="979" alt="last_merc2" src="https://user-images.githubusercontent.com/46383815/134444455-306952bd-90da-4637-bf90-484c99f8b48e.PNG">

13mins later it shows up

<img width="940" alt="last_merc3" src="https://user-images.githubusercontent.com/46383815/134444471-76e4f86c-9c6b-440a-baff-8967603de8c4.PNG">

If this service clock bothers you there's an option under **Tools - Trakt Management Tools** called **Force Trakt Sync to local database**.  This will sync on the fly and bypass the service clock so you do not have to wait.

Honestly I'm still not seeing a reason to make any changes here to Venom.  Even if you watch something in Venom, and both Venom and the Trakt addon post the scrobble to the Trakt api, I think the first received will be the one accounted for but they are so close in time sent it won't matter which it uses.  It is considered not wise to do this dbl scrobble post to Trakt api however but I've yet to see it cause an issue.  I also just tried the reverse...played in Venom while both Venom and Trakt addon attempted the post the scrobble.  It shows in Venom but after 15mins it never showed in Fen.  I'm not sure there's a service sync for that in Fen but I've reached out to him to chat on the matter.

**Comment by naudski** [comment]
Thanks very much for all your extensive testing!! I see now how this works and it indeed seems unnecessary to make this change in Venom. Now I know how to overcome the 15 min. service sync. Fen indeed does not scrobble by itself. It relies on the Trakt addon. As far as I know it does not have this particulier sync service.
