### ISSUE TITLE
Size sort low to high

### ISSUE THREAD

**Issue by Sunseng** [123Venom/plugin.video.venom#141]
Please add an option in setting for the size sort with reverse order from low to high like in Seren. 

In my country internet was slow so we need to play the smallest file size with best resolution to get a smooth streaming.

At the moment i can done it with edit the sources.py file with change the word in there, reverse=True into reverse=False, but Venom is a very active updating addons, and its will overwritten again after updating.

Thank you 🙏

**Comment by bolahanna44** [comment]
also sort with number of seeders

**Comment by 123Venom** [comment]
> 
> 
> Please add an option in setting for the size sort with reverse order from low to high like in Seren.
> 
> In my country internet was slow so we need to play the smallest file size with best resolution to get a smooth streaming.
> 
> At the moment i can done it with edit the sources.py file with change the word in there, reverse=True into reverse=False, but Venom is a very active updating addons, and its will overwritten again after updating.
> 
> Thank you 🙏

I've added this for next update

**Comment by 123Venom** [comment]
> 
> 
> also sort with number of seeders

due to the current sort methods for uncached torrents this would require a pretty decent re-write and one I'm not interested in embarking on.  I prefer the list sorted by quality then file size as it currently is. Then I can see the seeder count and chose which I'd like to cache.

**Comment by 123Venom** [comment]
> 
> 
> also sort with number of seeders

I went ahead and added an option to sort by seeders for you but I wanted to show you some info and just had inaccurate the info is that is given to us for seeder count.

<img width="1542" alt="seeders_discrepancy" src="https://user-images.githubusercontent.com/46383815/140864800-d48a0485-d516-42f7-9425-8f3d8fe6d79b.PNG">

<img width="965" alt="seeders_discrepancy2" src="https://user-images.githubusercontent.com/46383815/140864811-43ebe8d5-7250-46ca-b58d-8dbd216c92c1.PNG">

Exact same torrent...3 different sites.  Reported seeder count is 222, 18, 10..almost pointless but you'll have a setting.  Also to note that just because a seeder count is reported as 0 doesn't mean it won't cache..I've had plenty of failures and some successful.

**Comment by Sunseng** [comment]
Thank you very much. Venom is the best. 🙏👍👍
