### ISSUE TITLE
Unable to get latest Venom version on Kodi 18.9

### ISSUE THREAD

**Issue by james-nduka** [123Venom/plugin.video.venom#143]
Is that on purpose? Looks like no streams can be fetched now in v5.1.9

**Comment by drinfernoo** [comment]
The last version available for Kodi 18.x was 5.1.9, yes. If you're getting no streams, that's likely a different issue.

**Comment by 123Venom** [comment]
> 
> 
> Is that on purpose? Looks like no streams can be fetched now in v5.1.9
Not on purpose I just do not support Kodi 18 anymore and refuse to allow that to hinder my development of Venom for Kodi 19.

The problem is that v5.1.8 of "Fenom Scrapers" is a complete new scrape method that is NOT compatible with old Kodi 18 versions of Venom.  If you can not update to Kodi Matrix(19) you will have to download v1.5.7 from here....

[script.module.fenomscrapers-1.5.7.zip](https://github.com/Mr-Kodi/repository.fenomscrapers/blob/master/zips/script.module.fenomscrapers/script.module.fenomscrapers-1.5.7.zip)

Then disable Auto Updates or it will eventually happen again.  Personally you are missing out on nearly 6 months worth of some massive additions to Venom by staying on Kodi 18...I wouldn't recommend it.

**Comment by zemely** [comment]
Lately, I am getting "access_restricted" and "Unknown_source" messages trying to play scrappers. Cleaning all cache and providers seems to help but I have to do it after each episode. KODI 19.3, NVidia Shield. Tried to watch "Kingdom" TV Show and really had a hard time to stream

**Comment by 123Venom** [comment]
Those message sound like server response messages I flash when something of a problem from the debrid response takes place.  **access_restricted** is a little unsettling you are getting this response, you might want to check with your debrid provider.  Unfortunately I've never witnessed either of those server response messages so I'd have to nail the exact source link you tried to play so I need a bit more details to try and test it.  What debrid service?  This show **Kingdom** a title search turned up multiple shows of that title.  What is the release year of the show?  The first one from a title search was the **2014** premiered year.  There was also **2019, 2012, 2007** shows with that same title.  Then if you could screen shot to show me a source link that produces one of these messages and I'll test it.

**Comment by zemely** [comment]
I think to ask this question was very stupid of me. Yesterday I had discovered that my RD account has expired. I think that was my problem. I had purchased new subscription and will double check your addon in a few days. And at the time of this issue PM was not working so I had nothing. This is the first time I've missed my subscription.
What about trying to go into "Information" section from remote right click? It crushes KODI, not sur if it's KODI or Venom.

**Comment by 123Venom** [comment]
If you're getting crashes trying to bring up Kodi's "Information" screen on titles it's more than likely something in your setup.  Have you tested other addons to see if you get the same issue?  If you do not then I would try to disable the **reuselanguageinvoker** found in the Venom's settings under the category **Debugging**.  Sorry never seen Kodi crash there like ever.

**Comment by zemely** [comment]
Hello and thank you for your replies. Your suggestion seems to work, will keep testing. Since we are talking here, here is the question I was trying to find the answer for a while: is there any way yo change TV Shows setting to have source select instead of auto play? I was trying to watch a show and the first stream was in Italian and there is no way for me to go and pick the source in English, it's just keep playing Italian. I am pretty good with different addons settings but for the life of me, I couldn't find this setting for TV Shows. Movies are fine. Would appreciate an advise in this matter

**Comment by 123Venom** [comment]
Make sure the Default select action is set to **Source Select** here...

<img width="1084" alt="venom_1" src="https://user-images.githubusercontent.com/46383815/144920256-98288260-ec2c-4864-b43b-fddcc56068c5.PNG">

There is also a setting for **Enable PlayNext popup** under **Continuos Episode Playback Settings** here...

<img width="1129" alt="venom_2" src="https://user-images.githubusercontent.com/46383815/144920476-43181bc5-4157-47b9-90ab-aa2cbfcad2a3.PNG">

This setting actually will force AutoPlay to be hard coded **Enabled**.  My guess is you have that on.  Read the help file below it as it explains exactly how the whole Continuous playback works.

As far as this Italian audio track that was playing.  Can you screenshot the source link that did that for me?  I can chase that down.  Our intent is to keep Multi audio track cases we can properly identify.  If you setup Kodi so your preferred language is **English** Kodi should select that track on Multi audio track sources.  I have seen cases where this still fails and sadly I can not fix that because it's a gaff in the uploaded file.  It occurs if there are two tracks and both are labelled as **Default** so Kodi has no way to select the matching track and you then have to switch the tracks yourself....I've do on occasions and it simple.  It's possible the source link you had was a single audio Italian only version.  That's why I want to see it to determine if I can identify this source to fix it from happening.

**Comment by zemely** [comment]
OK, I think I finally realized what my problem was: the addon was not updated to the latest version and due to the crushing trying to go to UPDATE, I was not able to update it. SO, I've disabled and uninstalled addon, updated the repo and then installed new addon. Now it works like a champ. In fact, for what I am using it for, this is the best acting addon. Everything works, TraktTv is in synch every time.
Thank you very much for your time and replies

**Comment by zemely** [comment]
Hello again,attaching the screen shot where I am getting sources in Italian and Russian. In this case Italian. My KODI set with English language as a default and it's not just Venom, other addons show the same sources. 
I would appreciate any advice
Igor

    On Monday, December 6, 2021, 04:00:03 PM EST, 123Venom ***@***.***> wrote:  
 
 


Make sure the Default select action is set to Source Select here...



There is also a setting for Enable PlayNext popup under Continuos Episode Playback Settings here...



This setting actually will force AutoPlay to be hard coded Enabled. My guess is you have that on. Read the help file below it as it explains exactly how the whole Continuous playback works.

As far as this Italian audio track that was playing. Can you screenshot the source link that did that for me? I can chase that down. Our intent is to keep Multi audio track cases we can properly identify. If you setup Kodi so your preferred language is English Kodi should select that track on Multi audio track sources. I have seen cases where this still fails and sadly I can not fix that because it's a gaff in the uploaded file. It occurs if there are two tracks and both are labelled as Default so Kodi has no way to select the matching track and you then have to switch the tracks yourself....I've do on occasions and it simple. It's possible the source link you had was a single audio Italian only version. That's why I want to see it to determine if I can identify this source to fix it from happening.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 123Venom** [comment]
what screenshot?

**Comment by zemely** [comment]
Attached and below



    On Monday, January 3, 2022, 12:04:12 PM EST, 123Venom ***@***.***> wrote:  
 
 


what screenshot?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 123Venom** [comment]
idk what you are doing but you are not attaching anything.

**Comment by ShaVerZ** [comment]
I think he may be replying via email where attachments are ignored/blocked — I think.On 3 Jan 2022 17:29, 123Venom ***@***.***> wrote:
idk what you are doing but you are not attaching anything.
