### ISSUE TITLE
Scraping fail on 6.3.6

### ISSUE THREAD

**Issue by krijos** [123Venom/plugin.video.venom#145]
All movies I tried scraping failed (unless already cached) on 6.3.6 using FenomScrapers 2.0.2 and 2.0.1.
Rolling back to 6.3.5 with FenomScrapers 2.0.1 worked, while 6.3.5 with 2.0.2 failed.
Failed = scraping dialog did not trigger and returned "No stream available".

I keep logging disabled by default, but if you would like some log data I can enable it and redo my tests.

**Comment by ieswideopen** [comment]
Same issue, following

**Comment by 123Venom** [comment]
v6.3.5 will fail if used with v2.0.2 of Fenom Scrapers as they are not compatible due to a scraper change.  If you roll back Venom to v6.3.5 you must roll back Fen Scrapers to v2.0.1 also.

So onto Venom v6.3.6 with Fenom Scrapers v2.0.2.  Yes I'll need log data as it's anyone's guess without it.  I am not seeing the issue here on 4 devices.

**Comment by ieswideopen** [comment]
> 

Here you go https://paste.kodi.tv/zuzefiteze

**Comment by 123Venom** [comment]
```
[2021-11-19 19:17:31] [COLOR red][ Venom: ERROR ][/COLOR]: From func name: /resources/lib/modules/sources.py.getSources_dialog() Line # :409
                       msg : AttributeError -> type object 'source' has no attribute 'hasMovies'
```


The above error can occur under one of two cases.  You are either running an incompatible version of FenomScrapers per what I outlined, or it's possible I missed a scraper change for this new variable **hasMovies** in the class changes we made to all scrapers.  The easiest way to test for me was to run a new scrape using **All Providers** and bingo it failed and I received the same log error.  I then checked the scrapers and discovered a typo in **SCENERLS** hoster.  I'll will push an update to fix that and once I cured the typo all was fine.  That's why I could not duplicate the issue....I run the default scrapers and nothing more and imo to scrape with more than those 10 providers is pointless.  Not sure why you run hosters, frankly I think we need to remove them and eventually that may happen.

**Comment by 123Venom** [comment]
Fenom Scrapers v2.0.3 pushed to fix typo issue with SCENERLS.  That should take care of it.

**Comment by ieswideopen** [comment]
Thanks. Appreciate that.  I prefer your addon compared to the other s.
Maybe I'll take your advice and ditch the hostess :)

**Comment by 123Venom** [comment]
Try a scrape with the default providers only.  There's a nice Fenom Scraper option that will enable the default scrapers for you that I've put through some rigorous testing to determine the best ones for speed and content.  You will prob be pleasantly surprised with how much faster it will run if you've been using more than 10 torrents + hosters.  Hosters had their place but they're a dying source that are seldom needed anymore....Seren removed them completely and I've been eying ridding them myself.

**Comment by ieswideopen** [comment]
I'll do that. I live in the sticks and I've been slogging along with 3.5 mb
internet service and had every box checked off to get enough 720p HEVC
streams to watch a decent pic. Fortunately I just got 1.5 GB fiber to my
place, so it's been a world of difference.

**Comment by 123Venom** [comment]
ya that change will be a world of difference for you!!!

**Comment by ieswideopen** [comment]
I got to say, I've been using kodi for 16 years, since the early days of
xbmc. Your work is at the top of any of the addons I've used. It broke my
heart last year when you were talking of packing it in. I'm very glad
you've soldiered on.

Thank you

**Comment by 123Venom** [comment]
lol..ya I recall that day.  I got frustrated over TVDb's announcement they were going paywall only and right on the brink of Matrix going py3 only so I was beside myself if I wanted to invest all that required time to re-code the addon.  I really did want to just become a scraper maintainer only, which frankly I'm better at than anything else, but glad I chose to keep on rolling and fight my way through it.  TVDb's pushed off their claimed paywall only serivce going on a full year now and their so called paywall is now pushed off till 1st quarter of 2022....was suppose to be a year ago those assclowns.  I've come to HATE TVDb.

**Comment by ieswideopen** [comment]
TVDb better figure out a better way to monetize it, 'cause they'll go broke
if it turns into a paywall.

**Comment by 123Venom** [comment]
I'll never go near TVDb again...fuck them after the pot they stirred making claims to go paywall and then after all the panic they caused they just kept postponing it, sort of obvious they realized how badly they pissed off their user base.  They suck and I hope to see them crumble for it!!!!
