### ISSUE TITLE
Latest update makes Venom show just "No stream available."

### ISSUE THREAD

**Issue by cgcgcgcgcg** [123Venom/plugin.video.venom#151]
I tried multiple tv shows, Resyncing, clearing all cache, default Fenom scrapers, and all torrent scrapers.
Previous version worked just fine.

**Comment by cgcgcgcgcg** [comment]
Fen doesn't work too, so it's probably Fenom Scrapers that needs a fix.

**Comment by cgcgcgcgcg** [comment]
FenomScrapers dev said there is an error in the undesirables code in the latest version of FenomScrapers.
Disabling this option fixes this issue:
![k_20211210-152626](https://user-images.githubusercontent.com/38960370/145581652-f295aa6f-f297-4656-8cd2-a00f543e1ffb.png)

**Comment by drinfernoo** [comment]
@cgcgcgcgcg Which dev said this? 🤔

**Comment by xyzfre** [comment]
> FenomScrapers dev said there is an error in the undesirables code in the latest version of FenomScrapers.
> 
> Disabling this option fixes this issue:
> 
> ![k_20211210-152626](https://user-images.githubusercontent.com/38960370/145581652-f295aa6f-f297-4656-8cd2-a00f543e1ffb.png)
> 
> 

I was having the same issue no sources found I disable Undesirable like on your pic above and now everything is working normal thank you

**Comment by 123Venom** [comment]
@cgcgcgcgcg We've said no such thing.

This one is a mystery because I can not reproduce it scraping with default only providers or even All Providers.  Both Venom and Fen are scraping fine here.  I have a hunch that perhaps the re-write done to how the undesirables was stored in v2.0.1 might be an issue because v2.0.6 is the first version I've pushed where I added new undesirables to the base list that would use the new code.  It would only effect people that may have made changes so they have a custom stored list and might be why some will see this and some won't.

Sorry folks I'm going to need time to dig into this one.

**Comment by cgcgcgcgcg** [comment]
> @cgcgcgcgcg We've said no such thing.
> 
> This one is a mystery because I can not reproduce it scraping with default only providers or even All Providers. Both Venom and Fen are scraping fine here. I have a hunch that perhaps the re-write done to how the undesirables was stored in v2.0.1 might be an issue because v2.0.6 is the first version I've pushed where I added new undesirables to the base list that would use the new code. It would only effect people that may have made changes so they have a custom stored list and might be why some will see this and some won't.
> 
> Sorry folks I'm going to need time to dig into this one.
If it helps, this started after latest FenomScrapers update.
I clicked "FenomScrapers Default Providers", before disabling "Remove undesirables" but  that didn't work.
Sorry about the confusion about undesirables, I must have read it on some past issue, might have been a commenter not one of you guys.

**Comment by 123Venom** [comment]
Yes I'm well aware this all started last night.  We're looking into it...it's just damn hard to find when I can't reproduce it and the code handling that was not actually mine so this is going to take some time to resolve the matter.

**Comment by enginokurs** [comment]
Nothing works in movie section.  "Remove undesirables" option doesnt work either. Scraper finds sources but not playing.

**Comment by 123Venom** [comment]
Provide logs please

**Comment by ShaVerZ** [comment]
I had this problem 10 minutes ago after updating.... I re-authorised Trakt, exited Kodi, deleted Cache from within FireTV/Manage Installed Applications and restarted FireTV Box, all was fine after this....On 12 Dec 2021 08:08, 123Venom ***@***.***> wrote:
Provide logs please

**Comment by enginokurs** [comment]
I don’t know how to send the log file because I’m using firestick. Let me give an example. I searched for the movie "knives out" and the scraper found 106 torrents. but after that, when it came to playing the movie, no torrent files could be played. But this is not true for all movies. For example, in another movie, the scraper still finds torrents, but when the torrent I want doesn't work, it tries to run other torrents. By the way, I completely reset the kodi application and did a clean install of venom. but still i keep having these problems. For example, I also have the Seren add-on and I did not encounter any problems with that add-on. For example, I was watching the sopranos series on the venom add-on until 2 weeks ago, but when the add-on broke, I started watching it on the seren add-on, because the venom add-on cannot find any source for the sopranos series.

**Comment by 123Venom** [comment]
I just scraped Knives Out and played the first 5 links without issue.  I then tested s01e01 of the Sopranos and 47 cached torrents returned...first 5 played fine.  I can't duplicate your issue.  I might suggest a clean install.  Without logs its a guessing game

**Comment by ShaVerZ** [comment]
If you go into .../Tools/ Logging Tools/ Venom - Upload Log File to PasteBinthis will give you a link to the Venom Log File, same can be done for the Kodi Log File. I'm using FireTV and this works.....On 12 Dec 2021 11:06, 123Venom ***@***.***> wrote:
I just scraped Knives Out and played the first 5 links without issue.  I then tested s01e01 of the Sopranos and 47 cached torrents returned...first 5 played fine.  I can't duplicate your issue.  I might suggest a clean install.  Without logs its a guessing game

**Comment by enginokurs** [comment]
> If you go into .../Tools/ Logging Tools/ Venom - Upload Log File to PasteBinthis will give you a link to the Venom Log File, same can be done for the Kodi Log File. I'm using FireTV and this works.....On 12 Dec 2021 11:06, 123Venom ***@***.***> wrote: I just scraped Knives Out and played the first 5 links without issue. I then tested s01e01 of the Sopranos and 47 cached torrents returned...first 5 played fine. I can't duplicate your issue. I might suggest a clean install. Without logs its a guessing game —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

Ok i did as you just said. Uploaded log file to pastebin. is there anything else to do?

**Comment by enginokurs** [comment]
https://paste.kodi.tv/yanofehoye

**Comment by enginokurs** [comment]
I solved the issue. If you set the API language to a language other than English in the settings general tab, the software translates the name of the torrent you are looking for to that language and because the torrent names are in English, it seems that the scraper could not find the source. as in the case of the sopranos. I completely deleted the plugin and reinstalled it and the problem was solved. I think you need to fix about this, or you need to remove the option to change api language.

**Comment by 123Venom** [comment]
You would need to turn off the setting to remove single foreign audio tracks in FS for that change you made to work.

**Comment by cgcgcgcgcg** [comment]
I simply enabled "Remove undesirables" cleared Venom cache and enabled debug logging to prepare a log.
When I restarted Kodi, Venom worked fine, so I checked settings.xml like you suggested in: https://github.com/Mr-Kodi/repository.fenomscrapers/issues/26
The result now is:
```
 <setting id="undesirables.choice">400p.octopus,720p.octopus,1080p.octopus,alexfilm,amedia,audiobook,baibako,bigsinema,bonus.disc,casstudio.tv,courage.bambey,.cbr,.cbz,coldfilm,dilnix,dutchreleaseteam,e.book.collection,empire.minutemen,eniahd,.exe,exkinoray,extras.only,gears.media,gearsmedia,good.people,gostfilm,hamsterstudio,hdrezka,hdtvrip,hurtom,idea.film,ideafilm,jaskier,kapatejl6,kb.1080p,kb.720p,kb.400p,kerob,kinokopilka,kravec,kuraj.bambey,lakefilm,lostfilm,megapeer,minutemen.empire,newstudio,omskbird,.ost.,paravozik,profix.media,rifftrax,sample,soundtrack,subtitle.only,sunshinestudio,teaser,trailer,tumbler.studio,tvshows,ultradox,viruseproject,vostfr,vo.stfr,web.dlrip,webdlrip,wis
```

So I don't think the log might help you, Venom works fine for me.
