### ISSUE TITLE
Trakt and scraping issues 

### ISSUE THREAD

**Issue by Glen424** [123Venom/plugin.video.venom#152]
Venom is my number one addon and i use it for 95 percent of what i watch and i only use the others  if i cant find something on Venom ...so anyways ill try to keep it brief.  
1 Progress in Trakt section: very few of the tv shows i watch list in trakt progress, if i go into other apps such as asgard or crew the lists encompass all my shows.  ( i can supply a list of those shows if you need)
2 some shows such as "while the rest of us die"  and a few others..when new episodes come out, not only does it not list in Progress, and if i click on it from calendar section, it doesnt show the new episodes or allow me to scrape the new episodes as they dont even show up.
3 ive noticed since the app updated last night that im unable to scrape almost any episodes for any shows, this could just be a coincidence but i had to switch over to asgard to pull episodes today from Moonshiners and Legacies.   
im not getting any error messages apart from no stream available,  and ive not changed any settings in the last year so,  if you need logs or such let me know ( very very comfy with kodi but i might need a walkthru on logs) 
Thanks for all your time and effort in creating an excellent addon   i appreciate it every day!

**Comment by 123Venom** [comment]
Seems like **While The Rest Of Us Die** is a show that does not show up in Trakt Progress?  I marked S01E01 as watched and then S01E02 appears in my Trakt Progress fine.  What episode are you on?  Try clearing Venom cache.  

<img width="793" alt="20a" src="https://user-images.githubusercontent.com/46383815/145707699-04cca092-3416-443e-918c-cca65cb16d1a.PNG">

If you can me me a list of your shows not appearing in Trakt Progress I'll peak.  Also make sure while you are viewing the Trakt Progress list the pull out panel is set to **All Videos** 

What Calendar section are you referring to?  There's was a Calendar section in **My TvShows** before but that's been replaced by **Recent Episodes**, **Upcoming Episodes**, and **Season Premieres**.  What version of Kodi?  Please provide logs.

item 3 make sure you on on FenomScrapers v2.0.7 that was pushed last night to fix an issue with the undesirables list becoming corrupt that causes the issue you explain.

**Comment by 123Venom** [comment]
Sorry it has taken me some time to get back to you, holidays had me pretty busy.

I started with the first item You mentioned
>People Magazine investigates S05x13   (cannot mark watched)

https://www.themoviedb.org/tv/76458-people-magazine-investigates/season/5
https://trakt.tv/shows/people-magazine-investigates/seasons/5
https://thetvdb.com/series/people-magazine-investigates/seasons/official/5

As you can see from the meta TMDb lists an episode 13 while Trakt and TVDb does not.  The reason it will not mark as watched is because when the request is sent to Trakt the api does not believe it exists so nothing to mark.  I can not fix something like this when the meta providers are messed up like that.  You'd have to report the issue to them.

I then marked s01e01 of the following shows to see if they would show up in Trakt progress....
**Murder in the Heartland**
**What on Earth**
**People Magazine Investigates** (this one stuck because I tried to mark s05x13 at first so until meta providers fix this gaff nothing I can do)
**60 minutes**
**While the Rest of us Die**
**Still a mystery**
**Dateline Secrets uncovered** (Looks like missing ID)
**48  hours** (TMDb starts with Season 11)

<img width="983" alt="shows_progress" src="https://user-images.githubusercontent.com/46383815/147443819-7bf04934-c94d-45ea-bb04-da1734a57e8f.PNG">

All shows appeared for me except for **Dateline Secrets uncovered**.  That looks to be a missing ID trying to send to Trakt so it doesn't mark as watched without it.  I may be able to fix this one.  I have no idea why all these shows did not show up for you but all but one did for me.  You might try clear cache and forc Trakt Sync to local database.  Could be something corrupt.

**Comment by 123Venom** [comment]
Sorry it has taken me some time to get back to you, holidays had me pretty busy.

I started with the first item You mentioned
>People Magazine investigates S05x13   (cannot mark watched)

https://www.themoviedb.org/tv/76458-people-magazine-investigates/season/5
https://trakt.tv/shows/people-magazine-investigates/seasons/5
https://thetvdb.com/series/people-magazine-investigates/seasons/official/5

As you can see from the meta TMDb lists an episode 13 while Trakt and TVDb does not.  The reason it will not mark as watched is because when the request is sent to Trakt the api does not believe it exists so nothing to mark.  I can not fix something like this when the meta providers are messed up like that.  You'd have to report the issue to them.

I then marked s01e01 of the following shows to see if they would show up in Trakt progress....
**Murder in the Heartland**
**What on Earth**
**People Magazine Investigates** (this one stuck because I tried to mark s05x13 at first so until meta providers fix this gaff nothing I can do)
**60 minutes**
**While the Rest of us Die**
**Still a mystery**
**Dateline Secrets uncovered** (Looks like missing ID)
**48  hours** (TMDb starts with Season 11)

<img width="983" alt="shows_progress" src="https://user-images.githubusercontent.com/46383815/147443819-7bf04934-c94d-45ea-bb04-da1734a57e8f.PNG">

All shows appeared for me except for **Dateline Secrets uncovered**.  That looks to be a missing ID trying to send to Trakt so it doesn't mark as watched without it.  I may be able to fix this one.  I have no idea why all these shows did not show up for you but all but one did for me.  You might try clear cache and forc Trakt Sync to local database.  Could be something corrupt.

**Comment by Glen424** [comment]
Hey thanks for your time!  I know its a busy time of year and you probably have a real life job too!  anyways i woke up christmas morning here in canada, and found most of the episodes that i mentioned to you suddenly appeared in progress, save for  60 minutes and murder in the heartland I have no idea what has changed or why after all these months of them not showing up.  i sent off what you mentioned about people magazine to trakt in the form of an open ticket so hopefully they will sort that out!
thanks again for your efforts!
Glen

**Comment by 123Venom** [comment]
The cache prob reached it's duration and refreshed on it's own, unknown to you.  That's prob what may have brought them in now.

Nicely done raising a ticket to Trakt.  I wish more got involved in that process as it only benefits all.  idk if you noticed or not but **Dateline: Secrets uncovered** is another hot mess between TMDb and Trakt.  TMDb's seasons go 1, 2, 8, 9, 10...da fuck.  Trakt has all 10.

I did fix the id issue with that **Dateline: Secrets uncovered**.  That bug may well effect other obscure shows of this nature since TMDb was primarily movies at one time the older shows is still a bit lacking with them.  The id was missing at season level and I couldn't mark anything.  That's fixed for next release, as well as a few other tweaks to the unwatched counts.  If you enable unwatched counts you may have noticed that due to those missing seasons in **Dateline** the counts are all out of whack because the index order does not match up...simple fix so they gaff that again it won't screw up the counts.

Wife watches that reboot of **Fantasy Island** and the counts are a messed up on that one also.  Once I looked Trakt is 2 episodes behind while TMDb is current..little roll reversal there..lol.  People honestly do not know the hassles we go through when the meta from one provider to the next is all messed up.
