### ISSUE TITLE
Verrrrry slow since couple of weeks

### ISSUE THREAD

**Issue by marcelmah** [123Venom/plugin.video.venom#154]
Hi,

I've been using Venom for I don't know, a very long time now, works great!
Couple of weeks ago I noticed it taking a very long time, after you select an episode and the popup shows it searching, before the results are shown and then again after selecting the file to play it will show the popup again cycling trough all kinds of files before It starts playback, takes minutes.

I'm using the latest version (as of writing) with Trakt and Real Debrid.

Is this a known bug? or how can I help debug this?

**Comment by 123Venom** [comment]
Is this issue more pronounced with shows than movies?  There's a few nagging bugs in RD's endpoint that I've failed on every attempt to reach out to them for a resolution.  I see a nasty delay myself and have tested this issue **extensively** and it comes from checking the cached torrent status of pack files, and then again resolving for playback of the same. The larger the pack the worse it gets.  If you scrape a show where it's **status=ended**(GOT is a good test case) it will scrape for **show packs** and these can be HUGE.  AD and PM's api response is super fast, like .03 seconds to cache check 100+ torrents.  RD's api response varied anywhere from 20-60secs for the same list of hashes.  Sadly because of this I'm currently running with RD disabled because it's annoying to me and not one I can fix.  I've witnessed the same delay in Seren and Fen and even with those addons if I disabled RD, and run AD and PM only, both addons were considerably faster.  You won't see this issue in addons that do not support pack files because they're not sending these hashes to the endpoint, and yes I tested those as well to confirm.

Beyond the above issue I'm not aware of anything further.  My true opinion at this time is RD has turned to junk and I suggest giving either AD or PM a try.  There are 30 day vouchers flying all over the place for PM atm and you might try to snatch one up so you can test if this bug is what you are suffering from.  First run with both and then disable RD and see if it's considerably faster.

**Comment by ShaVerZ** [comment]
I've had a few problems with RD for the past few weeks, as you say, AD works flawlessly and I have AD is a priority over RD.....Have a great Christmas and a Fantastic New Year '22 – Thanks for all your hard work bringing us a great Add-on👍 On 24 Dec 2021 15:53, 123Venom ***@***.***> wrote:
Is this issue more pronounced with shows than movies?  There's a few nagging bugs in RD's endpoint that I've failed on every attempt to reach out to them for a resolution.  I see a nasty delay myself and have tested this issue extensively and it comes from checking the cached torrent status of pack files, and then again resolving for playback of the same. The larger the pack the worse it gets.  If you scrape a show where it's status=ended(GOT is a good test case) it will scrape for show packs and these can be HUGE.  AD and PM's api response is super fast, like .03 seconds to cache check 100+ torrents.  RD's api response varied anywhere from 20-60secs for the same list of hashes.  Sadly because of this I'm currently running with RD disabled because it's annoying to me and not one I can fix.  I've witnessed the same delay in Seren and Fen and even with those addons if I disabled RD, and run AD and PM only, both addons were considerably faster.  You won't see this issue in addons that do not support pack files because they're not sending these hashes to the endpoint, and yes I tested those as well to confirm.
Beyond the above issue I'm not aware of anything further.  My true opinion at this time is RD has turned to junk and I suggest giving either AD or PM a try.  There are 30 day vouchers flying all over the place for PM atm and you might try to snatch one up so you can test if this bug is what you are suffering from.  First run with both and then disable RD and see if it's considerably faster.
