### ISSUE TITLE
When stopping a episode for too long. It stars to play the next episode if i choose the same episode or a previous one.

### ISSUE THREAD

**Issue by GodsLikelyMe** [123Venom/plugin.video.venom#156]
This happens randomly, so I have not been able to grab a log.

It happens when I stop an episode for while. It will ask if I want to resume, but if choose to, it plays the next episode. I have tried to choose a previous episode and it still plays the next one of the last played

E.G.
Playing dexter 1 - 3

I stop it for while ( not pause)

Come back and try to resume. It ask if I wanna resume, but it plays the next episode.

Try to play the episode before and it plays the same episode from the last time. 

Feels like something is stuck. I have tried to grab a log but its random.  

Only fixes I have found is to stop it from playing and select sources or rescrape.

**Comment by 123Venom** [comment]
This is interesting and the reason is because I have seen this myself but it's been a few months since I experimented with it, and being so random, I left it alone because i did not have a solution.  First is would occur after stopping an episode and then going and playing a movie the next episode from that show would play instead of the movie.   I cured that condition but the one your seeing is related but a tougher issue to solve. 

Here's how the mechanics of that works and what randomly triggers it.  When we use AutoPlay with continual playback I have a pre-scrape in the background for the next episode...then it pre-resolves the next episode and places the url in a window property ready for when the current episode ends to immediately start playback of the next episode.  When you forcibly stop playback, in your case, Kodi is suppose to issue a callback `onPlaybackStopped()`.  When that callback is issued it triggers a function in the Venom player and clears that window prop so the pre-resolved url to play gets removed and you will not see the issue.  Kodi randomly fails to issue this callback and hence the window property is not cleared so that url is sitting there.  I need to come up with a fallback method when Kodi fails to make the callback.  Movies was easy to cure because going from episodes to movies I could force a window prop to clear in the movies module but with playing another episode, while still in the episodes module, is not possible without it wiping out the pre-resolved url every time playback is initialized and then it would be useless to even have it because it would never be used.

Hope I didn't lose you in all that.  At this time I do not have an answer how best to cure what I feel is a bug in Kodi.

I actually added a logging entry for the kodi.log and you will randomly see 
`'[ plugin.video.venom ] onPlayBackStopped callback'`
to signify the callback was properly issued by Kodi.  When it does what you describe you'll see that log entry missing and the callback was not issued by Kodi and hence the url is still sitting waiting to be played.

I'll give this some more thought and see what I can come up with but I don't suspect this to be a quick solve.  Thankfully it is random.

**Comment by GodsLikelyMe** [comment]
Followed what you said and don't expect some miracle. This is very random like you said. and is also a very easily fix from my point of view when it happens. I don't like to post issues without a log, but I'm glad you acknowledge it. 

Thought I was going a bit crazy at one point when I resumed an episode but had the next play and thought, " Hey, I haven't seen this yet" lol

**Comment by 123Venom** [comment]
lol..no you're not crazy and truth be told when I last visited this issue I sort of lazily gave up and said, "I'll wait and see if any user even detects it".  Well here we are I guess but took ya couple months since I knew about it..lol.  Some users prob have not spotted the issue because 1.) being random and 2.) It will clear under a lot of circumstances unless you stay inside the episode module till you return for playback then it will not.

I'm logging and toying with a few ideas now on it.  Another thing I'm spotting is the resolve window should NOT be coming up when your current episode ends.  Seems as if it's consistently pre-scraping the next episode but the pre-resolving seems to randomly not be successful.  The intent is the whole process is to be a background task so when your current episode ends the next_url is ready and waiting to start immediately.

**Comment by GodsLikelyMe** [comment]
Lol. Yea , it happened a few time before, but I always just tossed it up to being a fluke.  Sorry I brought this demon back up...  

Dude, dont forget to enjoy the holidays too. Feels like I unleashed something lol

**Comment by 123Venom** [comment]
na you're fine, name of the game.  I need to finally deal with this nuisance.  I got an idea I'm testing now how I can do my own test if you've stopped the video and assure that callback function is run at least once so stopped playback cases clears that window prop containing the next_url to play...fingers crossed and if so a solve happened a lot faster than I'd a guessed...lol.  I just get annoyed dealing with workarounds for what appears to be a Kodi bug.

**Comment by GodsLikelyMe** [comment]
More than happy to test.  We are binging the last season of Castlevenia lol

**Comment by 123Venom** [comment]
If you care to install this test version the issue should be fixed.  There's a few things that were related to your issue I enhanced some and also need a good testing.  The changes to focus on as follows...

1.) Verify that stopped episodes, that generate a resume point, no longer have the next pre-resolved episode stored in memory and begin playback instead of the selected episode to resume.
2.) Item 1 above use to also be an issue when you'd play a movie after an episode.  The pre-resolved next episode was not cleared.  My first fix was sort of a hack temp fix that the new method should be a long term solve but needs to be tested more.
3.) Previously resume point indicators/icons would randomly not display after stopping an episode and some times they'd show fine.  A new method seems to help solve this but I just discovered it also has a side effect and messes up the listItems. I ran ten test cases and my luck number 10 doubled up all the episodes so a container refresh seems to take the issue in another direction.  Watch for this as I may need to resort back to old method.

You can find the test version here.
https://github.com/123Venom/zips/blob/dev/plugin.video.venom-6.4.4.1.zip

**Comment by GodsLikelyMe** [comment]
Will try it out. Not sure how much I'll be using during this weekend though. 
Have a happy new year!

**Comment by 123Venom** [comment]
Same here...taking a break for awhile but wanted to toss up what I had done for now.  Take your time.
