### ISSUE TITLE
venom 319 playback controls display

### ISSUE THREAD

**Issue by bjbca** [123Venom/plugin.video.venom#16]
Kodi 18.4
Estuary skin
Extended art on or off
during playback of tv episodes, when controls are brought up, time and duration show in upper right but
Name (year)
S#E# : Episode#
do not show in upper left corner, I kinda miss that feature...
 Thanx for a great addon

**Comment by drinfernoo** [comment]
This is a skin issue.

**Comment by 123Venom** [comment]
Dr...skin issue with Estuary?  Ive not check his issue yet but will.

**Comment by bjbca** [comment]
Im thinking it has to do with clearart/clearlogo in player, with extended artwork enabled the episode name populates the upper LH screen but when dissabled that area is blank, the setting disables the download of the extended data but it hasnt been disabled in player so with no data the player leaves that area blank... am i on the right track ?

**Comment by drinfernoo** [comment]
Having extended artwork turned on wouldn't keep the add-on from knowing what episode it's playing... Does Estuary even show clearlogo?

**Comment by bjbca** [comment]
Clearlogo does work in Estuary,
So as a test i removed all reference to clearart, clearlogo and discart in player.py, i turned off extended art in settings and cleared all cache and played an episode... and the upper left corner of the screen populated with the info i was looking for, so the setting to turn off extended art would have to be coded in player also.

**Comment by 123Venom** [comment]
ya but you have to back up a little and understand the whole code path.  First back in episodes.py I preset the extended artwork to '0' in the event one two conditions occurs.  1.) either fanart.tv does not return a value, or 2.) You've disabled extended artwork.  So in you case those values should be '0' from the start.  Then once the dir list itens is populated the dict is iterated and all null or '0' values are removed.  So once the player.py module runs we see things like this for clearlogo.
 
`			clearlogo = '0'
			if 'clearlogo' in meta: clearlogo = meta.get('clearlogo')`

so here it's preset to '0'..then checked if it's in the meta dict.  In your case it will not be present so the clearlogo value should be remaining at '0'.  This should not be a problem with the skin.  I just ran a quick check, cleared cache and tested an episode of "game of Thrones" as I know it's full of extended artwork.  clearlogo does show in Estuary but I still get no episode info in upper left corner.  I then checked a known exo fork that I know does not even pass clearart to display in the player.  There's the year and S?E? info in upper left corner.  So far as I can tell this is an Estuary bug.  It's placing clearlogo in the upper left corner instead of the episode info even if no clearlogo is available.  I think that's just bad skinning to do that.  I can prob add a check for the skin and void any clearlogo being set at all as a work around for the problem.  I use Silvo and I know it does not do that nor does Aura.  They should have a dedicated placeholder for clearlogo not replace other info when it's present because that is exactly what it's doing, even when it's a '0' value...eww.  They should put it in center if exists.  What kills me is even a '0' value and Estuary takes a dump on this

**Comment by bjbca** [comment]
Thnx for the help, I can just run with my modded player but i may check out silvo, I have already modded estuary as i didnt like it showing the apps on my android devices... i will have to see what silvo looks like on them...

**Comment by 123Venom** [comment]
Silvo is a decent skin.  Some think it old but Mike is still very actively developing it and just released an update last night.  I like it for it's unmatched widget controls..size and transparency...etc.  If set up right it can be very clean.  Play around with the homescreen controls if you're a neat freak.  His text for the homescreen is huge so I use icons with labels and it shrinks the size down allot.  Aura, or Aura mod is also decent skins...tried Aura mod as it's popular but chose to stay with what I'm use to plus keeping Silvo avoids pissin off the wife and that's a huge plus!

**Comment by 123Venom** [comment]
actually I'm having an afterthought on a workaround fix.  I was about to hard code a solution once I fetch the skin in use but then I wondered what if some other user prefers to see that logo vs. the episode info?  I'm thinking I may add a setting option to disable clearart in player.

**Comment by bjbca** [comment]
cool, my problem is i have a few setups of my own to look after plus some family, i do a few mods to addons and get everyone set up and look after them so if a skin has too many settings to worry about then it complicates things for family ;)

**Comment by 123Venom** [comment]
`			if skin == 'skin.estuary' and self.media_type == 'episode':
				item.setArt({'thumb': thumb, 'poster': poster, 'tvshow.poster': poster, 'season.poster': poster, 'fanart': fanart})
			else:
				item.setArt({'clearart': clearart, 'clearlogo': clearlogo, 'discart': discart, 'thumb': thumb, 'poster': poster, 'tvshow.poster': poster, 'season.poster': poster, 'fanart': fanart})`

more testing and it's actually clearlogo being used and over-writting the episode info.  I've made it so it keeps the clearlogo for movies but when Estuary skin in use and episode being played they are remobed and not passed to the skin.  This cured the issue!  I reported the problem so hopefully they'll fix the skin where the true problem lies.

**Comment by 123Venom** [comment]
I'm going to close this issue as a workaround is done and will be included in next release.

**Comment by bjbca** [comment]
awesome
