### ISSUE TITLE
Movie Thumbs

### ISSUE THREAD

**Issue by adamosborne83** [123Venom/plugin.video.venom#166]
Hey,
Now I do know know if this is a Venom issue or Auramod Skin issue.
So apologies.
See the video, so basically some of the thumbs of movies do not show, but if I go on them it does (see insidious) but then it eventually downloads...
The movies are from my library which I use Universal Movie Scrapper, if that makes any difference. 

What could this be? Apologies for vague as always. 

https://imgur.com/a/kDKRX6m

**Comment by 123Venom** [comment]
It's neither a Venom issue nor a skin issue.  When you scrolled back onto the item was the artwork not there then?  Yes each item then produced a poster. Take a wild guess what that means?

You must be using the preferred fanart.tv images as they'll take a tad longer to load.  I prefer the TMDb poster/fanart images myself and use the setting to prioritize them because they're smaller, load faster, and I give to shits about being anal art wise.  What you are witnessing is the delay load time for the fanart.tv images to load coupled with your ISP incoming speed.  There's nothing an addon can do there about it and your paid ISP speed will have an obvious effect.  Once it's cached they'll subsequently load faster.  You should know this obvious issue!!!
