### ISSUE TITLE
Up next from widget (direct progress scraping)

### ISSUE THREAD

**Issue by jake93evans** [123Venom/plugin.video.venom#167]
Hi,

**Conditions:** 
Default select action: Auto-play (venom)
Next up pop-up: enabled (venom)
Direct progress scraping: enabled (venom)
Play next video automatically: episodes (kodi)
Widget in use: My shows > Progress
Skin: Arctic Horizon

When playing from within the Venom add-on, the next up pop-up appears.
When selecting "Play from here" on a widget, the next up pop-up appears.
When just tapping the 'enter' key (play) from the widget, the next up pop-up **does NOT** appear.

Hoping it's just me missing something?

Thanks in advance

**Comment by 123Venom** [comment]
That is actually by design.  If you want the Enter button to launch as if you used **Play from Here** then you need to go to **"System - Settings - Player - Videos - Play next video automatically"**.  Then select **Episodes**.  Basically what that does is turn the **Enter** button into **Play from Here** while on an Episode listItem, and obviously it won't effect Movie behavior.  There's a help file in the settings right below where you enabled the **PlayNext** pop-up and it was explained to you there.  Still a good read you might want to check out.
