### ISSUE TITLE
Re-Authenticate Trakt Access

### ISSUE THREAD

**Issue by senecawarrior** [123Venom/plugin.video.venom#168]
First I apologize if this was addressed elsewhere. I have searched and searched and could not find anything. I am getting a pop up that states "Re-Authenticate Trakt Access" every time I open Kodi. I've re-authenticated which fixes the issue for that sessions but it then comes back after I watch a show or exit Kodi and go back in. I've cleared cache, reset defaults, and even uninstalled/re-installed kodi from scratch and still get the pop up. I can confirm this appears to only be happening on my Shield Pro. The firesticks do not get the pop up.

**Comment by 123Venom** [comment]
Did your Shield get the Experience 9.0 update that installs Android 11?  A lot of people having problems with that and I've refrained from updating my own Shield on account of this.  I'm not getting the **Re-Authenticate Trakt Access** notification.  Oddly that notice ONLY pops when the Trakt token is required to refresh due to a **401** and the token generally is good for 3 months.  The only other time I've seen this occur is a Trakt list you may have liked where the user later sets the list to **private** and returns a 401.  I've added code to avoid that condition so it should not be your problem.  I need the venom.log in bebug mode, not Kodi's debug mode but in Venom's settings under **logging** has one specifically for Venom logging.

**Comment by senecawarrior** [comment]
Thanks for the quick reply. 

Actually I did more reasearch and found, like you said, the issue with android 11 on the shield. I have since signed up for the hotfix releases that are supposed to fix the many issues. One being “issues with Kodi 3rd party addons”. Once I get the update I will post back. I will also get the debug info when I get back home. 

Again I appreciate the quick response. Venom is the best add on out there!

**Comment by 123Venom** [comment]
I was afraid you were going to say that.  A lot of people still complaining the hotfix still did not cure the problems they were having.  I setup a bran new shield last week for a family member and the first thing it wanted to do was an Experience 9.0 update.  I gambled and figured if it doesn't work I'd just factory reset and start over.  Everything went fine so it seemed to me that if the system was Android 11 first and Kodi, with addons, installed after it's fine.  Sure looked to me like Android 11 upgrade after the fact breaks the hell out of it.

**Comment by xyzfre** [comment]
Makes a lot of sense after updating my Nvidia shield to android 11 on my end I was having random crashing issues on Kodi start up so I did a back up of my build deleted Kodi and this time I decided for the first time to get it from the android store,, restored my build and don't want to jinx it but ever since then it's been running smooth and finally my sound bar displays Dolby digital and prior to this Nvidia shield update my sound bar would never display Dolby on the display panel it was always PCM,, just wanted to share that info in case it helps anyone but after this update to Android 11 I definitely suggest deleting Kodi and reinstalling it,, and I'm also on Hotfix number 3

**Comment by senecawarrior** [comment]
I too just got hotfix 3. Kodi was unbelievably slow so I deleted and reinstalled completely. Also (knock on wood) have not had the re-authenticate message pop up. I will keep what you said in mind as a last ditch if I get the issue again. If I do get the pop up again I’ll try factory reset if it resets to 9 I’ll leave it alone! If it makes me start on 11 I’ll install Kodi after. I can also report my mouse toggle and ssd issues I’ve been fixed with the hotfix. 

Thanks for tips!
Cheers!

**Comment by 123Venom** [comment]
> I will also get the debug info when I get back home.

I'd definitely be curious to see that before you make any system changes.  My hunch is it's a permission issue related to Android 11.  I'm not sure Venom's logging would report that however but it might give me an indication of what's going on.

**Comment by senecawarrior** [comment]
Absolutely! Sorry for reinstalling without thinking of getting you the logs. (It’s been one of them days) if i get the pop up again I will get you the logs. 

Thanks for all the help.
