### ISSUE TITLE
Very strange, maybe not venom

### ISSUE THREAD

**Issue by adamosborne83** [123Venom/plugin.video.venom#169]
When I click on any videos that I have downloaded to mu library, suddenly I cannot watch them.

Trending etc still work.

Https://paste.kodi.tv/ahosolakaj

**Comment by 123Venom** [comment]
ERROR <general>: CVideoPlayer::OpenInputStream - error opening [/storage/F843-1010/Android/data/org.xbmc.kodi/Movies/Hannibal (2001)/Hannibal.2001.strm]

I thought perhaps you'd had the infamous file permission problems associated with latest Android 11 but your log says you're are on Android 9.  You are unable to access the .strm files with that path so time to start troubleshooting that issue.

**Comment by adamosborne83** [comment]
> `ERROR <general>: CVideoPlayer::OpenInputStream - error opening [/storage/F843-1010/Android/data/org.xbmc.kodi/Movies/Hannibal (2001)/Hannibal.2001.strm]`
> 
> I thought perhaps you'd had the infamous file permission problems associated with latest Android 11 but your log says you're are on Android 9. You are unable to access the .strm files with that path so time to start troubleshooting that issue.

I am sorry for being the bain of your life with your issues section 🤣🤣🤣 I was the same with Auramod when they were making their changes too. It was very odd, as it only suddenly started happening, also previous movies in my library were working, just the new additions were coming up with it.

**Comment by 123Venom** [comment]
post the content of your `Hannibal.2001.strm` file. strm files are playing fine here.  I even added that exact title..

<img width="1505" alt="hannibal5" src="https://user-images.githubusercontent.com/46383815/152659168-8f5f417d-d1ef-48e7-89f5-3530ab6398fd.PNG">

As you can see mine reads the strm file fine and your produces an error.  I'd investigate that path.
Also I changed my setup to AuoPlay since your log is not indicating a sourceSelect.xml skin was loaded.  Try changing in Venom to Source Select vs. AutoPlay.  Does the source select load at all?  Do you see the bottom 2 context menu options from Venom in this pic....

<img width="1081" alt="hannibal2" src="https://user-images.githubusercontent.com/46383815/152659236-47d657d5-4d74-4ff2-a7c9-804d832a0c31.PNG">

If those options are missing you either do not have the Venom Global Context addon install or the item is not being detect by Venom as belonging to it when it reads the strm file.  I still say there's a failure with your storage location.

**Comment by adamosborne83** [comment]
> post the content of your `Hannibal.2001.strm` file. strm files are playing fine here. I even added that exact title..
> 
> <img alt="hannibal5" width="1505" src="https://user-images.githubusercontent.com/46383815/152659168-8f5f417d-d1ef-48e7-89f5-3530ab6398fd.PNG">
> 
> As you can see mine reads the strm file fine and your produces an error. I'd investigate that path. Also I changed my setup to AuoPlay since your log is not indicating a sourceSelect.xml skin was loaded. Try changing in Venom to Source Select vs. AutoPlay. Does the source select load at all? Do you see the bottom 2 context menu options from Venom in this pic....
> 
> <img alt="hannibal2" width="1081" src="https://user-images.githubusercontent.com/46383815/152659236-47d657d5-4d74-4ff2-a7c9-804d832a0c31.PNG">
> 
> If those options are missing you either do not have the Venom Global Context addon install or the item is not being detect by Venom as belonging to it when it reads the strm file. I still say there's a failure with your storage location.

In regards to it being my storage, I find it odd that old library downloads would work, and newer not... we are only talking within the last 24hrs.

I've not played with my settings. 
![20220205_212152](https://user-images.githubusercontent.com/78307374/152659586-9a33efc9-2c4c-4ff3-90be-d4ca1b08429f.jpg)

![20220205_212219](https://user-images.githubusercontent.com/78307374/152659592-0a4ac69c-786e-4eac-85a4-1fdb3bfbb9c1.jpg)
![20220205_212315](https://user-images.githubusercontent.com/78307374/152659596-c4a7a917-b1ef-43da-b4a7-6c827a4852db.jpg)



Https://paste.kodi.tv/bemoreyiri

**Comment by 123Venom** [comment]
Looks like your latest log you've changed usb storage device?  The amount of file read errors in your logs is crazy, many of which are not even Venom related files.  Breaks the record for the most **invalid handle** errors I've ever seen.  You have a serious device issue and not an addon issue.  You're even getting numerous timeout errors accessing official Kodi resources, for example...

`ERROR <general>: CCurlFile::Stat - Failed: Timeout was reached(28) for http://mirrors.kodi.tv/addons/matrix/script.module.inputstreamhelper/resources/icon.png`

Yet I can load that url into a browser and get the icon instantly.  You did try to restart it right?  Maybe try a kodi.log in debug mode.  Also toss up the **venom.log** file and set it to debug in Venom's settings and not **Normal** mode.

**Comment by adamosborne83** [comment]
> Looks like your latest log you've changed usb storage device? The amount of file read errors in your logs is crazy, many of which are not even Venom related files. Breaks the record for the most **invalid handle** errors I've ever seen. You have a serious device issue and not an addon issue. You're even getting numerous timeout errors accessing official Kodi resources, for example...
> 
> `ERROR <general>: CCurlFile::Stat - Failed: Timeout was reached(28) for http://mirrors.kodi.tv/addons/matrix/script.module.inputstreamhelper/resources/icon.png`
> 
> Yet I can load that url into a browser and get the icon instantly. You did try to restart it right? Maybe try a kodi.log in debug mode. Also toss up the **venom.log** file and set it to debug in Venom's settings and not **Normal** mode.

I'm using a fire cube, I deleted kodi and reformatted the usb, but still the same issues. I've ordered a new usb stick so I will let you know today. BUT as I hate to admit it(haha) I think you're right. As I added a TV show to my library, on the firecube and it loaded instantly.

**Comment by adamosborne83** [comment]
Out of interest and just for my curiosity, do you have any idea why previous library items would play and not new? Also, I am guessing the reason your trending etc work is due to it be Web based info?

**Comment by adamosborne83** [comment]
Got a new USB and new Firecube and all working. Seems your app is still all ok, let you off.

Cheers as always.

**Comment by adamosborne83** [comment]
OK, I take it back........ as soon as I put scrapping into background, that's when it comes up with the errors!!!

**Comment by adamosborne83** [comment]
Omg what's happening. 

Https://paste.kodi.tv/eqojenubev

**Comment by adamosborne83** [comment]
This makes no sense 

https://user-images.githubusercontent.com/78307374/152691784-5a87dfe0-01e5-46b7-a05b-8d27e7c587ad.mp4


Https://paste.kodi.tv/ewalaxevar

**Comment by 123Venom** [comment]
Your log is once again so loaded with various errors I'd be here to Christmas trying to slowly debug things to find out what happening.  You got a slew of connection errors to TMDb, OMDb, RD that are not addon related.  You're also using a skin that is prob my **least** favorite to deal with on account of my feeling was it was to buggy for me and stayed away from it, I'm seeing skin errors in there also.  You have not provided the logs I've asked for.  I wanted to see the content of that strm file that suffered a failed to read file error so something was hosed back then on your old usb stick, but never got that either.  The latest log seems to indicate reading the strm file error is gone but as I said the errors are so vast there's far more going wrong here for you.  When you switched to background scraping your skin appears to be using a busy dialog and the background scraping process becomes hidden. Venom does not call a busy dialog and that issue does not happen for me with Silvo skin...petty but an observation.

I'm sorry but every attempt to reproduce this here has failed and playback is fine for me.  I'm also sorry but I will not attempt to use that skin.  I'd honestly try another skin if it were me, but the list of things I'd do would just absorb way to many hours.  You could try to switch your settings to stop using that skin's Info - Play button and setup so that just the enter button initiates playback.  See if anything changes as a test.

 You also commented....
 >as soon as I put scrapping into background, that's when it comes up with the errors
 
 go back to foreground scraping because it's apparent to me the skin is doing something on account of that busy dialog hiding the process so who know what else it might be doing especially if that triggers the errors as you say.
 
 Background scraping was not hidden by a busy dialog for me, to which Venom does not call one.
<img width="1285" alt="Hannibal_11" src="https://user-images.githubusercontent.com/46383815/152701681-8ef9bdb2-8ff8-4e7b-b077-3d0b5933df6e.PNG">
 
 Silvo is not the most attractive skin but for me I'll take a bug free hideous skin over dealing with the numerous hassles I had with AuraMod when I gave it a test drive, and put plenty of time in on it before saying NO.  AH is a nice skin, clean and not buggy.

**Comment by 123Venom** [comment]
Against my better judgement I still had the AuraMod repo install so I decided to install the skin once more and test it, which installed v1.1.7 and matches what your log also claimed you are on.  Playback for me was still fine and also does not exhibit the busy dialog issue I saw in your vid.

<img width="1349" alt="Hannibal_AM 1 1 1" src="https://user-images.githubusercontent.com/46383815/152710143-ec5c2d7b-1bd2-4d6b-b57b-d0ed56a13e3e.PNG">

Then I had a peak at the log....
<img width="1614" alt="Hannibal2_AM 1 1 1" src="https://user-images.githubusercontent.com/46383815/152710202-d8f723d9-5ddd-4571-8696-83209f9ce78c.PNG">
Clean and not what I see in yours.

BUT...and BIG BUT AT THAT.  Once I switched back to my Silvo skin I'm now seeing nasty log errors
<img width="1337" alt="20a" src="https://user-images.githubusercontent.com/46383815/152710253-4f37ff4e-4060-4b32-9f15-57714404a04e.PNG">

Upon investigating of what is now different than before I examined my running addons.
<img width="931" alt="20b" src="https://user-images.githubusercontent.com/46383815/152710280-4d3e276b-6769-4484-b620-9003e157cfec.PNG">

**Skin Helper Service** and **Skin Helper Service Widgets** are only used by AuraMod and Silvo does not use them.  Those two suckers are wreaking havoc on my setup.  Since the skin is not in use I disabled them and used **Reload skin**.  Errors are gone and I'm back to before.  That 5mins of playing with AuraMod was enough for me to realize why I WILL NEVER use that skin.

**Comment by adamosborne83** [comment]
> 

Thanks again and apologies for the announance I bring. I'll try AH skin

**Comment by jaimsitecom** [comment]
I’m getting the same error. So what is the resolution for this?  Newly added scraped episodes into the kodi library get the error. But the past weeks’ episodes have no problem playing. Weird. What i do now is i had to delete the ‘non playing’ .strm file and re-add it. Just then it will play as it should.

**Comment by adamosborne83** [comment]
> I’m getting the same error. So what is the resolution for this? Newly added scraped episodes into the kodi library get the error. But the past weeks’ episodes have no problem playing. Weird. What i do now is i had to delete the ‘non playing’ .strm file and re-add it. Just then it will play as it should.

Ive just opened a new issue, see if this makes sense to you, this is how i have overcome this issue.

**Comment by 123Venom** [comment]
> I’m getting the same error. So what is the resolution for this? Newly added scraped episodes into the kodi library get the error. But the past weeks’ episodes have no problem playing. Weird. What i do now is i had to delete the ‘non playing’ .strm file and re-add it. Just then it will play as it should.

Logs?

**Comment by jaimsitecom** [comment]
> Sounds to me like it prob will happen again. Could be something in the update process but all that it does is create the new item and write the strm file. When the new item is added does it appear with new meta as if all is fine? If a broken case occurs seeing the content of that **strm** file file would be real helpful...but none of yall giving any assistance thus far getting me requested files..lol

Yes the error occured again, here’s the log:

https://mega.nz/file/gZJXFIhK#o1MJ1icCWbWsXyXNasoSMEz6NhpDdvg_WeIEQSaSBtA

thanks!

**Comment by jaimsitecom** [comment]
And here are my vemom log:

https://mega.nz/file/EEp2SB5R#KL0dvU6iOs2hI6sbMkrNEBA9rFH6I46olOgCS57cjy8

Broken .strm 

https://mega.nz/file/tJ5CGCpJ#G7GfVlkLPsCklJblWdE0qLnjMkf-nKdHFoCN1xsm4ls

Working .strm

https://mega.nz/file/MdpmxCAK#Sz-kj7ZZB7tf5UGFBqZR9snopn0M6wUVd0fWNddFv00

Ty!

**Comment by jaimsitecom** [comment]
just a side note, i deleted the non working .strm files, cleaned library, downgraded back to venom 6.4.7 (unclicked auto update), then ran the venom library update at settings/tools to have the deleted episodes added back again to kodi library.... and it works!  i think i'll stick with 6.4.7 for now and check again tomorrow if the newly added strm files will play or not.

thank you

**Comment by adamosborne83** [comment]
> just a side note,
> 
> 1. i deleted the non working .strm files,
> 2. cleaned library,
> 3. downgraded back to venom 6.4.7 (unclicked auto update),
> 4. then ran the venom library update at settings/tools to have the deleted episodes added back again to kodi library....
> 
> and it works! i think i'll stick with 6.4.7 for now and check again tomorrow if the newly added strm files will play or not.
> 
> thank you

If only I was as good as you with logs Mr Venom wouldn't be pulling his hair out with me, I'm away for next couple days, be very interested if .7 works with Auto update keep us updated please.

**Comment by 123Venom** [comment]
Reviewing the library module for this case I offer the following....

  There's a **strmFile()** method that writes those **strm** files and the code is called be it a new item add or one that is an update add item, the same method is used.  The fact the exact same code is doing a "now you see me, now you don't" I can not explain.

   The fact that `argv` is also not adding that plugin path on some is a bit odd and the only thing I've seen do random odd stuff like that is the setting `reuselanguageinvoker`  There's a setting in the `debug` category to flip this off.  You might try that...but...I also went over commits I've done since you're saying v6.4.7 does not have the issue.  That also struck me odd since I've not touched anything library related in some time.  The commits are showing a file has returned that is not suppose to be there.  The module has the same name as a class inside the library module and could be in conflict causing random issues.  I had deleted that file since it's no longer in use and it seems to have returned in v6.4.8, long story short I deleted it from a working folder but not my repo folder I use to build the zips from so it got put right back in.  I'm not sure if either of you are capable of deleting the file named `lib_tools.py` from the `modules` folder but that would be the first thing I'd try...then if that doesn't cure it I'd try turning off that `reuselanguageinvoker`.  Just a thing to note is that setting offers a considerable speed boost so you'll notice the addon slow down a bit when it's disabled.  If you can not access to delete the file I can created a test zip to install with the file removed but it will only be to test if it's causing conflict.  Let me know.

**Comment by 123Venom** [comment]
I went ahead and made you guys a test zip with the file in question removed.  Please test and let me know if any change to when an update takes place.  Make sure the strm file is created and the content of the strm file contains the plugin path previously shown to you.

https://github.com/123Venom/zips/blob/dev/plugin.video.venom-6.4.8.1.zip

**Comment by jaimsitecom** [comment]
> I went ahead and made you guys a test zip with the file in question removed. Please test and let me know if any change to when an update takes place. Make sure the strm file is created and the content of the strm file contains the plugin path previously shown to you.
> 
> https://github.com/123Venom/zips/blob/dev/plugin.video.venom-6.4.8.1.zip

Thanks a lot! Will try this asap. Then report what happens. 

Thanks again!

**Comment by jaimsitecom** [comment]
> I went ahead and made you guys a test zip with the file in question removed. Please test and let me know if any change to when an update takes place. Make sure the strm file is created and the content of the strm file contains the plugin path previously shown to you.
> 
> https://github.com/123Venom/zips/blob/dev/plugin.video.venom-6.4.8.1.zip

Yup. This is good!  Worked well like 6.4.7 

The kodi library added clean .strm files and didn’t give out error anymore. 

Once, thanks a bunch!!! More power to you!

**Comment by 123Venom** [comment]
I had a bad feeling it was that carry over file that should not have been in there.  I have a working Kodi folder where I make code changes and see in real time....then a desktop folder where I run a a custom `xcopy.bat` file to bring in the new code work.  The problem is xcopy brings the revised/work files over but if I deleted a file from the kodi folder it is NOT then deleted from my desktop folder.  An issue I am well aware about just flying by seat of my pants I often forget to delete the source from **BOTH** locations.  Deduct it from my pay I'm ok with that...ohh wait yall get my many hours of time for freeeeeee.  How bout an even exchange is I get a nice break from hearing about library BS for 1 month!?!?!

**Comment by adamosborne83** [comment]
> I had a bad feeling it was that carry over file that should not have been in there. I have a working Kodi folder where I make code changes and see in real time....then a desktop folder where I run a a custom `xcopy.bat` file to bring in the new code work. The problem is xcopy brings the revised/work files over but if I deleted a file from the kodi work folder it is NOT then deleted from my desktop folder. An issue I am well aware about just flying by seat of my pants I often forget to delete the source from **BOTH** locations. Deduct it from my pay I'm ok with that...ohh wait yall get my many hours of time for freeeeeee. How bout an even exchange is I get a nice break from hearing about library BS for 1 month!?!?!

Haha, well I installed it before work this morning, so when I get home i will let you know. Then and only then I will leave you alone 😔  and I thought you liked our company.

**Comment by 123Venom** [comment]
>well I installed it before work this morning, so when I get home i will let you know

well based on @jaimsitecom response below we have to believe it works fine now. 

>This is good! Worked well like 6.4.7

>Then and only then I will leave you alone

Really?  Bet I block you you'll leave me alone..lol

**Comment by jaimsitecom** [comment]
> I had a bad feeling it was that carry over file that should not have been in there. I have a working Kodi folder where I make code changes and see in real time....then a desktop folder where I run a a custom `xcopy.bat` file to bring in the new code work. The problem is xcopy brings the revised/work files over but if I deleted a file from the kodi work folder it is NOT then deleted from my desktop folder. An issue I am well aware about just flying by seat of my pants I often forget to delete the source from **BOTH** locations. Deduct it from my pay I'm ok with that...ohh wait yall get my many hours of time for freeeeeee. How bout an even exchange is I get a nice break from hearing about library BS for 1 month!?!?!

Sorry man. I apologize to bother you with this. I feel bad now annoying and taking your time. Sorry again.

**Comment by adamosborne83** [comment]
> > I had a bad feeling it was that carry over file that should not have been in there. I have a working Kodi folder where I make code changes and see in real time....then a desktop folder where I run a a custom `xcopy.bat` file to bring in the new code work. The problem is xcopy brings the revised/work files over but if I deleted a file from the kodi work folder it is NOT then deleted from my desktop folder. An issue I am well aware about just flying by seat of my pants I often forget to delete the source from **BOTH** locations. Deduct it from my pay I'm ok with that...ohh wait yall get my many hours of time for freeeeeee. How bout an even exchange is I get a nice break from hearing about library BS for 1 month!?!?!
> 
> Sorry man. I apologize to bother you with this. I feel bad now annoying you with Kodi library and taking your time. Sorry again.

Don't worry mate this is why @123Venom gets paid the big Bucks from us 😉 🤣🤣🤣.

Did you have auto update enabled out of interest when it added the trakt updates?

**Comment by adamosborne83** [comment]
> > well I installed it before work this morning, so when I get home i will let you know
> 
> well based on @jaimsitecom response below we have to believe it works fine now.
> 
> > This is good! Worked well like 6.4.7
> 
> > Then and only then I will leave you alone
> 
> Really? Bet I block you you'll leave me alone..lol

Don't be like that haha. You know the respect I have 😁

**Comment by jaimsitecom** [comment]
> > > I had a bad feeling it was that carry over file that should not have been in there. I have a working Kodi folder where I make code changes and see in real time....then a desktop folder where I run a a custom `xcopy.bat` file to bring in the new code work. The problem is xcopy brings the revised/work files over but if I deleted a file from the kodi work folder it is NOT then deleted from my desktop folder. An issue I am well aware about just flying by seat of my pants I often forget to delete the source from **BOTH** locations. Deduct it from my pay I'm ok with that...ohh wait yall get my many hours of time for freeeeeee. How bout an even exchange is I get a nice break from hearing about library BS for 1 month!?!?!
> > 
> > 
> > Sorry man. I apologize to bother you with this. I feel bad now annoying you with Kodi library and taking your time. Sorry again.
> 
> Don't worry mate this is why @123Venom gets paid the big Bucks from us 😉 🤣🤣🤣.
> 
> Did you have auto update enabled out of interest when it added the trakt updates?

Yes auto update is ON. So evertime i turn on Kodi, Venom will check for new episodes based on my trakt collection. 

😊

**Comment by adamosborne83** [comment]
Sorry it just doesn't seem to work for me on auto update, tried it today and still errors. 
I will just do manual update weekly, no issue, I am so happy otherwise.
If you lived in Bristol I'd buy you a beer Venom haha. 

Https://pastry.kodi.tv/latihivuye

Ps... no more talk of library, 😉

**Comment by 123Venom** [comment]
Folks that is a change team Kodi did to Matrix.  If an update was installed from a zip AutoUpdates will stop working.  To get AutoUpdates back you MUST install from repo.

**Comment by jaimsitecom** [comment]
> Folks that is a change team Kodi did to Matrix. If an update was installed from a zip AutoUpdates will stop working. To get AutoUpdates back you MUST install from repo.

Hi again. Last question, is the version 6.4.8.1 the last of its kind that will have the kodi library support feature?  I tried to install 6.4.9 and it went back to giving playback error because the .strm produced dont include venom url at the start of the script. 

Anyways, i just went back to v6.4.8.1 and will be happy to get stuck at it. 

Thanks always and also sorry for always buggin you with this.

**Comment by adamosborne83** [comment]
> Folks that is a change team Kodi did to Matrix. If an update was installed from a zip AutoUpdates will stop working. To get AutoUpdates back you MUST install from repo.

Sorry I meant Auto Update on Libr*ry, not the Venom update :)

**Comment by 123Venom** [comment]
I did not touch anything library related so I had a peak to make sure the module issue did not return.  The files are still gone from latest v6.4.9 and that's about all that would make the issue return.  I frankly have no idea and I'm exhausted from dealing with library Integration.  If you want my true opinion I'd give The Oath a try.  He seems to stick with maintaining it with far greater interest than I, he might even use it himself.  Or give TMDb Helper a try as it also supports library integration.  I honestly want to be done with it and remove it because these headaches frequently happen.

**Comment by jaimsitecom** [comment]
> I did not touch anything library related so I had a peak to make sure the module issue did not return. The files are still gone from latest v6.4.9 and that's about all that would make the issue return. I frankly have no idea and I'm exhausted from dealing with library Integration. If you want my true opinion I'd give The Oath a try. He seems to stick with maintaining it with far greater interest than I, he might even use it himself. Or give TMDb Helper a try as it also supports library integration. I honestly want to be done with it and remove it because these headaches frequently happen.

Ok gotcha. Thanks anyways.

**Comment by 123Venom** [comment]
>I tried to install 6.4.9 and it went back to giving playback error because the .strm produced dont include venom url at the start of the script.

Well that makes me think it was pure coincidence then that when I removed those files the problem went away.  This now sounds more like an issue with argv due to the `reuselanguageinvoker`.  `argv[0]` is what puts the plugin path in front and that invoker is known to cause some argv issues.  Try turning that feature off in settings under `Debug`.  Let the update add some titles and check it.  If that does fix it then I can hard code the plugin path to be written instead and that might solve it.

btw..I tried to look at that log and it's a dead link.

**Comment by adamosborne83** [comment]
> 

OK, i will try that, and let you know after work this eve what's happened.
Thanks as always and love how committed you are.

**Comment by jaimsitecom** [comment]
> > I tried to install 6.4.9 and it went back to giving playback error because the .strm produced dont include venom url at the start of the script.
> 
> Well that makes me think it was pure coincidence then that when I removed those files the problem went away. This now sounds more like an issue with argv due to the `reuselanguageinvoker`. `argv[0]` is what puts the plugin path in front and that invoker is known to cause some argv issues. Try turning that feature off in settings under `Debug`. Let the update add some titles and check it. If that does fix it then I can hard code the plugin path to be written instead and that might solve it.
> 
> btw..I tried to look at that log and it's a dead link.

Tried the Oath! Uninstalled it after 5minutes of testing. Their own ‘scraper module’ is so buggy and too slow compared to fenomscraper. Had to go back to Venom!!! Hahahaha 

installed 6.4.9 again and disabled the debug feature ..languageinvoker. Will see later if it will add working .strm files when the library updates and checks on new tv episodes. 

Again, so sorry to bother you with this. It’s just that nothin compares to your Venom addon. Feature and speedwise…simply the best. 

Thanks again.

**Comment by jaimsitecom** [comment]
> > I tried to install 6.4.9 and it went back to giving playback error because the .strm produced dont include venom url at the start of the script.
> 
> Well that makes me think it was pure coincidence then that when I removed those files the problem went away. This now sounds more like an issue with argv due to the `reuselanguageinvoker`. `argv[0]` is what puts the plugin path in front and that invoker is known to cause some argv issues. Try turning that feature off in settings under `Debug`. Let the update add some titles and check it. If that does fix it then I can hard code the plugin path to be written instead and that might solve it.
> 
> btw..I tried to look at that log and it's a dead link.

Well, Venom updated the kodi library just now and turning off the language invoker (yesterday) in the debug didnt prevent the .strm to get ‘broken’ when being added in the kodi library. 

so i am just gonna downgrade again to 6.4.8.1 and stay here for good. 

Thanks again!

**Comment by adamosborne83** [comment]
> > > I tried to install 6.4.9 and it went back to giving playback error because the .strm produced dont include venom url at the start of the script.
> > 
> > 
> > Well that makes me think it was pure coincidence then that when I removed those files the problem went away. This now sounds more like an issue with argv due to the `reuselanguageinvoker`. `argv[0]` is what puts the plugin path in front and that invoker is known to cause some argv issues. Try turning that feature off in settings under `Debug`. Let the update add some titles and check it. If that does fix it then I can hard code the plugin path to be written instead and that might solve it.
> > btw..I tried to look at that log and it's a dead link.
> 
> Well, Venom updated the kodi library just now and turning off the language invoker (yesterday) in the debug didnt prevent the .strm to get ‘broken’ when being added in the kodi library.
> 
> so i am just gonna downgrade again to 6.4.8.1 and stay here for good.
> 
> Thanks again!

Yea, I've lost the 8.1 zip so I went back to .7 and all good.

Thanks Venom for everything and your app is awesome.
I cannot even begin to comprehend the amount of your free time that goes into this.

Thanks again. 
Now I will leave you alone about Library haha

**Comment by 123Venom** [comment]
You guys want to give this one last try?

https://github.com/123Venom/zips/blob/dev/plugin.video.venom-6.4.9.3.zip

In that version I hard coded the plugin path and does not use `argv[0]` to do it for me.  If that doesn't cure it I'm at a loss to know why.

**Comment by adamosborne83** [comment]
> You guys want to give this one last try?
> 
> https://github.com/123Venom/zips/blob/dev/plugin.video.venom-6.4.9.3.zip
> 
> In that version I hard coded the plugin path and does not use `argv[0]` to do it for me. If that doesn't cure it I'm at a loss to know why.

Will do, and thanks again for doing this even though you hate library.
Would you like me to post a log of the movie working in .7 version.

Then remove the title, cleanse the library and then add it via the auto update with the above zip and if it doesn't work to compare?

Or would you prefer library to never be mentioned again?  🤣

**Comment by 123Venom** [comment]
lol..kind of sad I had to resort to that.  I have no clue why even when the invoker is disabled, as you guys tested, that `argv[0]` would randomly drop adding the plugin path to the created strm files.  All I did was manually force adding the plugin path and say fuck `argv[0]` doing it for me.  Hate to point fingers but imo that's a Kodi bug right there...same function doing different shit from one minute to next....welcome to Kodi.

We just need confirmation from @jaimsitecom  that it also works for him also.  If so I'll include it in next update.

**Comment by adamosborne83** [comment]
> @adamosborne83 btw why did you double reply to my question about trying v6.4.9.3? When I first saw that quickly I thought I was seeing 2 replies thinking you and @jaimsitecom both responded it works and we could move forward, but I had to do a double take myself and noticed you replied twice about it working...why idk but it just looks goofy you doing that. Confusing chap you are.

Like to keep you on your toes 🙃

**Comment by 123Venom** [comment]
You have a warped sense of that.  I'd kindly you ask you to refrain from being weird and playing games :-)

**Comment by jaimsitecom** [comment]
I confirm 6.4.9.3 works great.  

Thanks so much!

**Comment by 123Venom** [comment]
Thanks @jaimsitecom . That confirms it so it will be in next update.

**Comment by jaimsitecom** [comment]
> Thanks @jaimsitecom . That confirms it so it will be in next update.

Thanks again for everything.
