### ISSUE TITLE
Feature request: sorting titles without leading articles.

### ISSUE THREAD

**Issue by betatester3016** [123Venom/plugin.video.venom#17]
The Kodi wiki lists that:

2.5.4 sorttokens

allows you to specify additional tokens that will be ignored at the start of lines during sorting.

Adding for example the sorttoken "the" will causse "the", "the." and "the_" being ignored at the start of titles or names when sorting items, in both video and music libraries.

The addon seems to disrespect these instructions in advancedsettings under Leia 18.4. I understand it is only  a cosmetical issue but would it be possible to allow the addon to sort this way?

Great job on the addon furthermore. I like your improvements on the load times!

https://kodi.wiki/view/Advancedsettings.xml#sorttokens

Thank you.

**Comment by drinfernoo** [comment]
That setting inside `advancedsettings.xml` almost certainly applies only to local library content.

Venom does appear to be ignoring the article "the" in lists though.

**Comment by 123Venom** [comment]
Can you give a more specific example where "the" is not ignored in sorting?  I recently updated one of my sort functions where I missed it and thought all were covered except some movie tmdb collections that seemed like an api response issue

**Comment by 123Venom** [comment]
waited 3 days for response..no response so I'm closing this.

**Comment by betatester3016** [comment]
I wasn't feeling well so I took some time to rest. Here is a combined screenshot, some stuff blurred out for copyright reasons. That's what I see on the same box when using the Trakt collection option under My TV Series. I'm running both under CoreElec 9.2.0 Stable (Leia 18.4) on a Tanix TX3 Mini H 2G/16G. I hope this helps. As I said, it's a cosmetics so not a big issue.

![screenshot1000](https://user-images.githubusercontent.com/49594656/65380696-19f9e480-dca6-11e9-88e3-8304fe8b089b.png)

**Comment by betatester3016** [comment]
I wasn't feeling well so I took some time to rest.

Here is a combined screenshot, with some stuff blurred out for copyright reasons.

This combined screenshot represents what I see on the same unit when using the _(Trakt) Collection_ option under _My TV Series_ with 2 different, up to date, add-ons.

Both add-ons use the same resolver and scrapper (ResolveUrl and OpenScrapers).

I'm running both add-ons under CoreElec 9.2.0 Stable (Leia 18.4) on a Tanix TX3 Mini H 2G/16G.

I also was able to replicate this behavior on a Nexbox A95X 1G/8G under both LibreElec (Kodi 17.6) and CoreElec (Kodi 18.4) as well as on an Android Tablet with both Kodi 17.6 and Kodi 18.4 Android apk's.

I remember in the past the Genesis add-on or one of its forks like Zen having a setting to turn this sorting on or off.

I hope this helps.

As I said, it's not a big issue. I just would like you to be aware of this.

![screenshot1000](https://user-images.githubusercontent.com/49594656/65380856-30a23a80-dcaa-11e9-92ca-4d358ffdbefa.png)

**Comment by 123Venom** [comment]
I will look into this and get back to you.  I only have a few items in my own collection and will have to build a list to see why the sorting is not correct for "Collections".  I did a complete re-write of the sorting to add more options and it's possible I missed a list for the new function or have a mistake in it that needs to be looked at.  Is that the only list you see this sort issue in?

and I'd like to make you aware of a few things.
1.) what resolver and scrapers are in use by an addon has nothing to do with lisitem sorting.
2.)  I would not call Exodus Redux an up to date addon.  It's not been touched since last March and does not appear it may get an update.
3.) The sorting in Venom vs. Redux is completely different. One uses a simple internal sort() function and Venom has a completely re-written function of it's own to handle a far greater amount of sorting options.  You'll see the additional sort options in the settings comparing the two addons as you did, which by the way is no longer a good idea as allot of the code is now very much different.  Comparing Venom to Redux is like comparing Venom to Seren....two different animals you can't fairly compare.

**Comment by 123Venom** [comment]
took one look and spotted the mistake.  I had ignore {the, an, and} for "tvshowtitle" but not "title" so some lists were not using the proper sort.  It's already fixed and test.  Trakt watchlist also indicated the problem when I switched to "Title" sort method "Ascending".  I'm wrapping up some other changes so this will be included in next release, which I hope to push tomorrow night.

**Comment by betatester3016** [comment]
I figured it would be something easy, just hard to explain. Thanks for your feedback. The picture was to provide a visual of what was going on. 

I had it on the first test machine happening both under ascending and descending so I didn't bother verifying with the other setups. I also checked if a view change (list, thumbnails, wide view, etc) would affect things differently but that's a negative. I could have told you that earlier. I also didn't bother checking the other branches like recently watched or genres because usually they are all unified.

Do you want me to keep an eye open for other things?

**Comment by 123Venom** [comment]
sure
