### ISSUE TITLE
Venom slowing my Shield Pro down to the point where it is unusable

### ISSUE THREAD

**Issue by Ebonlore** [123Venom/plugin.video.venom#174]
Used to love Venom then a few version ago it started bogging down my box like no tomorrow.

I'm guess it is the rather large Trakt account that I maintain.

Disabling venom returns the box back to normal so it's definitely the culprit.

Is there any reason why Venom's service.py would be pegging my box so heavily?

**Comment by 123Venom** [comment]
I run Venom on my Shield Pro, and two win10 setups and suffer no bog down at all and all on Kodi 19.4.  The service sync runs every 15mins at default but there's a slider in settings that can be adjusted but honestly it should not need it.  The sync is designed to first request your trakt activities and it compares the timestamps written to database version the timestamps received from the api.  If a change in activities is detected a sync will occur but if no changes since last check it technically does nothing.

 Provide logs and I'll see if anything unusual is going on.  Might even try a fresh install but I've not even done one a single time on my Shield since I've started.
