### ISSUE TITLE
Feature Request: TMDB Lists

### ISSUE THREAD

**Issue by Visual-Wizard** [123Venom/plugin.video.venom#18]
Love the addon; thanks for taking the time to maintain it.

I humbly request that you consider adding a new feature.

In the past; addons like Elysium and Uranus had a feature which would allow users to add TMDB lists to their menu. Essentially; this would allow users to browse through movie and television show lists that they or other people had put together.

It was a super awesome feature, but there are no addons which currently work well that have it.

I would guess that it wouldn't be too hard to integrate into Venom seeing as how they were similar addons.

**Comment by 123Venom** [comment]
I can see bout adding TMDb user lists in the near future.  Thought crossed my own mind recently.  The Martial Arts section in "Collections" is my own custom list I did on TMDb so allot of the required code for api v4 lists I already wrote for that so it would be partly done.  Have to be duplicated in the My Lists sections but can be done.

**Comment by 123Venom** [comment]
Just thought I'd keep you posted on progress, because I finally got round to this today and was allot more work than I thought.  I had to do some homework on the TMDb api for users own lists and it's not as simple as an api key.  You need a session_id and to get that you first need a token, then you have to authorize/validate the token.  Then you can get the session_id.

Few screen shots of what's it's looking like thus far.
New settings options
![Capture5](https://user-images.githubusercontent.com/46383815/66262068-6a456c00-e7a7-11e9-9c03-2b5a8a017877.PNG)

TMDb watchlist and some of my custom lists
![Capture21](https://user-images.githubusercontent.com/46383815/66262075-834e1d00-e7a7-11e9-9a02-792e9ee14cc7.PNG)

There's still some issues to work out.  TMDb defaults to 20 list items per request and my custom lists I have 27 so I need to add a "for" loop for a second page to have them all under the 'My Movies-My Lists" but oddly the online api tools will not advance for me to page2.  I was almost considering making it's own TMDb list category but wasn't sure that was good idea either...benefit would have page a next page indicator.

**Comment by 123Venom** [comment]
After really getting into the nitty gritty with these lists I'm coming to the conclusion TMDb suck ass for lists.  They are problematic and not without their fare share of errors. Take this list for example https://www.themoviedb.org/list/118017.  It's part of the "Movies-Collections-Martial Arts-Actors" group.  When I created that list all was good with the 64 titles I added to it.  Something has now fried most all my TMDb lists as only 32 titles are shown in that one list but it still claims there's 64 titles in it...wtf.  Same exists on web site and also returned in api response...dropped 50% of them.  I even searched for the dropped titles and they still exist with the same exact id so why they are dropped from the custom lists I have no clue.  You can't like YMDb lists like Trakt, can't search for lists, wth good are these lists especially if they break shortly after you create them?  I posted the issue to TMDb forum but if no response I'm ridding this problem as fast as I wrote the code to add it.  It's rubbish!!!

**Comment by 123Venom** [comment]
and there's the reason most devs don't bother with TMDb lists...cause they're junk!

**Comment by 123Venom** [comment]
ok sorry but I gave my opinion and this is turning into shit real fast with TMDb errors and problems so closing this and lost interest.  Moderators are skipping over my posted issue so why waste anymore of my time if they do not care.
