### ISSUE TITLE
Failed to mark as watched

### ISSUE THREAD

**Issue by skynetisnow** [123Venom/plugin.video.venom#180]
First off, thank you so much for everything you do @123Venom, you've been my all time favorite developer for years and I appreciate everything you do!

I'm having an issue where a new show, one in particular, "Fails to mark as watched in Trakt" inside Venom. When I check Trakt, the episode is marked as watched like normal. The show still shows up in my unwatched list in Venom no matter what. I even tried removing the show completely from my Trakt list and watched history and re-adding it and then manually marking the episodes as watched again. The show in question is The Witchfinder if that makes any difference. The rest of my shows act as normal. Thanks again!

**Comment by drinfernoo** [comment]
Reauthorize Trakt.

**Comment by 123Venom** [comment]
Yes providing me with the show title is always a good thing, the more details you provide the easier time for me chasing it.  Anyway the issue appears to be Trakt meta.  That title is a mess.  Trakt has 3 instances of it and two of them the tvdb_id is wrong.  I attempted to mark SS01E01 as watched and it also failed.  I then logged the data and got this for a response....


```
[2022-03-24 13:51:00] [COLOR red][ Venom: INFO ][/COLOR]: From func name: resources.lib.modules.trakt.markEpisodeAsWatched() Line # :1014
                       msg : imdb=tt11133202
[2022-03-24 13:51:00] [COLOR red][ Venom: INFO ][/COLOR]: From func name: resources.lib.modules.trakt.markEpisodeAsWatched() Line # :1015
                       msg : tvdb=416510
[2022-03-24 13:51:00] [COLOR red][ Venom: INFO ][/COLOR]: From func name: resources.lib.modules.trakt.markEpisodeAsWatched() Line # :1020
                       msg : result={'added': {'movies': 0, 'episodes': 0}, 'not_found': {'movies': [], 'shows': [], 'seasons': [{'seasons': [{'episodes': [{'number': 1}], 'number': 1}], 'ids': {'imdb': 'tt11133202', 'tvdb': '416510'}}], 'episodes': [], 'people': [], 'users': []}}
```

You can see in the bottom result is the api's response and `added` key should have returned `episodes: 1` but is `0`.  You do however find it in the `not found:` key.  So for some reason Trakt api does not believe it exists on their server.


Trakt's 3 instances of the show...
https://trakt.tv/shows/the-witchfinder-159689
https://trakt.tv/shows/the-witchfinder
https://trakt.tv/shows/the-witchfinder-2022

That last link above does have the correct ID's for all three meta providers so I'm a bit stumped why Trakt api is taking a dump on finding it.  The only thing I can think of is if you look close at that 3rd links web page Trakt lists the date the last `Refresh Data` occurred.  That date is yesterday.  It's possible that item was added yesterday and it's just not in Trakt's cache data for lookup just yet...only a guess because it should find it but doesn't.

Sadly something like this issue I can not fix.  Trakt needs to sort this out.  It might self correct by days end if my hunch above is right.  In the mean time it should be reported to Trakt they have 3 instances of that show....not good and imo I've been seeing a steady increase lately in this duplicate problem.

**Comment by TapMeDead** [comment]
Had this issue with "The Haunting of Bly Manor", it took a long long time until I was able to set it watched. It just sat there laughing at me since I watched it. Just set it watched maybe a month ago. The show is from 2020.

**Comment by skynetisnow** [comment]
Thanks again @123Venom I appreciate you taking the time to look at it.

**Comment by skynetisnow** [comment]
@TapMeDead haha I might just move the show to a different list instead of letting it stare back at me every day 🤣

**Comment by 123Venom** [comment]
I ended up reporting it..but the more the merrier.

**Comment by 123Venom** [comment]
@skynetisnow just to keep you informed I found a little work around.  First I've re-checked that show to see if that **Refresh Data** case I mentioned was just not in Trakt's cache and it still fails to be found on Trakt's server.  I then went on to do a little testing.  Since I send both imdb and tvdb ID's I decided to see what happens if I only use one.  When I send the post to Trakt with the imdb ID only it fails.  If I send the post to Trakt using tvdb ID it works...that's whacked and imo a bug that this show thus far has turned up suffering from the issue.  I had created a ticket with Trakt on the matter and alerted them to what I found.  In Venom I added a fallback check for the condition and currently I have it marking and unmarking for this series.
