### ISSUE TITLE
No titles returned when searching for movies

### ISSUE THREAD

**Issue by mrledwards** [123Venom/plugin.video.venom#181]
I am receiving an empty search result when trying various movies. Venom log available at https://paste.kodi.tv/qocigabobu.
Log shows a 404 error when searching.

Kodi log file: https://paste.kodi.tv/tedaquqega

Running venom 6.6.5.4, kodi 19.4 on ubuntu 21.04 system.

**Comment by 123Venom** [comment]
Searching for titles or scraping for source links of a title?  Once that's confirmed give me a few title cases so I can test on my end.

That 404 error in your venom.log is the result of a list attempting to load and it first fetches each listItem ID from TMDb.  This usually happens when Trakt returns incorrect ID's.  Unfortunately I can't fix incorrect ID's returned by a meta provider, they have to.  Do you have **Debugging-Log Level** set to **Debug(Extra Info)**?  Make sure it's set to that.

Your kodi.log indicated nothing of value for the issue.  Looked like you played all TVshow stuff

**Comment by mrledwards** [comment]
Thanks for the reply, it was searching for titles that was the issue. Even a very broad search term, and looking at various options within discover movies was only returning titles i have in my trakt watched list or collection list. I'll get some further logs with a higher logging level also.

**Comment by mrledwards** [comment]
I had time to quickly check with extra logging info for two search terms "evil" and "world" to see if any titles were returned.
Log file for this is at https://paste.kodi.tv/libuvovala.
Oddly it is only this device that is having this issue even after a complete reinstall of the addon.

**Comment by mrledwards** [comment]
Hi, a second reinstall of kodi and venom, including deleting all files and now it is working. There must have been some issue with the previous reinstall i did. I'm sorry for taking up your time, and i am unsure why the previous full reinstall also had issues unless there was a conflict with an addon i haven't installed yet. I'll close this issue.

**Comment by 123Venom** [comment]
I got 44 titles returned searching for **Evil** and 37 for **World**.  I'm really not seeing any issue here.

You have one error being logged that ends with **Line # :917**.  That's not an error to be to concerned over.  It's just implying TMDb returned another html response I'm not error capturing.  I log capture the `404's` but one is getting through.  If you are not getting any returned titles on those two you try to re-auth Trakt but I'd be shocked if that does anything honestly because you'd be having all sorts of Trakt problems as it is but worth a shot.

You might also want to check to make sure when viewing the list your pull out panel is not set to **watched**, and should be on **all videeos**.  That would do this as well

One thing I may consider is switching the search from Trakt to TMDb in time.

**Comment by 123Venom** [comment]
> Hi, a second reinstall of kodi and venom, including deleting all files and now it is working. There must have been some issue with the previous reinstall i did. I'm sorry for taking up your time, and i am unsure why the previous full reinstall also had issues unless there was a conflict with an addon i haven't installed yet. I'll close this issue.

ohh glad it's resolved...looks like our last replies crossed.
