### ISSUE TITLE
Duplicate show title

### ISSUE THREAD

**Issue by TheGuru276** [123Venom/plugin.video.venom#188]
Not sure how or where else to request this but I'm hoping you can improve finding the correct links for shows that have the same name.

Would this be via an entry in your remakes database?

The particular show I'm trying to get episodes for is Starstruck (2021), the UK TV series but all I get is episodes for Starstruck (2022) the reality talent show

**Comment by TapMeDead** [comment]
@TheGuru276 I just entered Starstruck and all that came up is the show you want, (2021).
![Screenshot_1](https://user-images.githubusercontent.com/99356645/162611758-9c15a550-2e52-47dd-87a6-f4ff595a5f2b.png)

**Comment by TheGuru276** [comment]
> @TheGuru276 I just searched for tv shows, entered Starstruck, and all that came up is the show you want, (2021). Well the reality show also came up in the search, but without a cover image. If you happen to have watched your Starstruck show before, make sure you are not hiding watched shows, this is a check in the left-hand pop-out menu
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/99356645/162611758-9c15a550-2e52-47dd-87a6-f4ff595a5f2b.png)

Thanks for taking a look. I noticed you use RD like most other users. I'm an AD user so maybe it's just what AD can find. I haven't tried for a few weeks so I'll take another look and see what I get in the results.

**Comment by TapMeDead** [comment]
@TheGuru276 I don't have AD to test, the Dev himself does though, he might pop in, I am sure he is sleeping now though.

**Comment by TheGuru276** [comment]
@TapMeDead Sleep, who needs that. LoL

Looks like I've gone and added a season torrent to AD at some point to find sources. So I might delete it from my cloud and see what happens on a new search.

**Comment by 123Venom** [comment]
I enabled AD only for the test below and all sources were the 2021 desired show.  I can't think of a setting that would be allowing that other show in.  I even reviewed the 37 uncached torrents results and still not a single source for that 2022 reality show.

<img width="1384" alt="starstruck" src="https://user-images.githubusercontent.com/46383815/162628217-d337de8b-181f-44c7-8b47-9c6abcb1ef48.PNG">

The show in question is not a known reboot. You can review the list of reboot shows here.
https://github.com/123Venom/plugin.video.venom/blob/516ce4906be9b32f7940589a69d720f8e718e44a/resources/lib/modules/source_utils.py#L217

There was a recent fix to BITCQ that did exhibit a similar behavior and was fixed in v2.1.8.  It's possible you have cached results from the bug in that scraper still.  Did you try clearing all providers?  A Rescrape does the same but ONLY for the given item.  The BITCQ bug could have straggler bad sources for a number of shows and why I suggest clearing all providers.

Try that and report back.

**Comment by 123Venom** [comment]
Here's a link to the similar case that was happening with BITCQ.  It would return similar, but wrong show sources.

https://github.com/123Venom/plugin.video.venom/issues/183#issuecomment-1090887538

**Comment by TheGuru276** [comment]
Thanks for your time. As it happens I had just recently done a clearing of the addons caches for another issue and I am also getting the correct results now. Maybe I had last looked during the BITCQ issue. So just to be clear it's not common to get results from other identically named shows as a previous show 'Taken' has done the same thing to me ages ago. I've successfully watched Taken (2008) and then came across Taken (2002) but only ever got 2008 results.

**Comment by 123Venom** [comment]
ya I'm fairly sure that when you cleared all cache it wiped out your providers cache which housed some bad results from the BITCQ bug we fixed.

As for that `Taken` show condition, yes that one is going to be a problem.  First it's not a reboot, totally different shows yet exact same name.  Scene releases GENERALLY do not add a year in the shows source title.  They do however GENERALLY add a year when it's a reboot, like `The Flash` for example.  The reboot of that most sources will be for ex....

`The.Flash.(2014).Season.1.S01.(1080p.BluRay.x265.HEVC.10bit.AAC.5.1.Vyndros)`
Here we can distinguish which show version it is because they included the year.  That's where the setting option in Venom for `Require year in known reboot shows` can come in handy and prune out the old version with no year in it.  The setting can also drop some valid cases when some not so smart uploader chose to not use a year, but you'll still be more accurate in the results with the setting on.

Now back to your `Taken` example.  I ran a scrape of the 2002 show and got this....
`Taken-.S01..2017..Complete..FHD..1080p..x264..WebDL..Multi-6-Lang..MultiSUB.-PHDTeam`
Unfortunately this uploader put the damn year after the season and HIGHLY uncommon to do so.  Just like movies the year in most all uploads is after the title.  Even for reboot shows look at `The Flash` above and year is after the title.  I can tell you that during title matching I Parse off everything after the season/episode info so sadly the year vanishes and I can't match it.  I do check the year but if it's not available it's assumed a non reboot case so it passes.  This case got thru because of where the fool put the year.  Unfortunately do to the rare times that will happen I'm not touching that.

Then I peaked at the uncached torrents list and a whole bunch of this sort of format condition shows up.
`Taken-S01E01-1080p-WEB-DL-DD5-1-H264-RARBG`
So looking at the info we have to deal with above ask yourself, "How could anyone possibly know what show of those two cases that is?"  You can't!

Honestly I wish all shows got uploaded with a year...period..but they do not.  The rule most uploaders follow is year after title on reboots and that imo is still a problem and things like your `Taken` case being a prime example of the failures it creates.  They add the year for movies but only do so for shows on reboots, go figure and dumb imo.  There's just nothing we can really do about it.  Those kind of shows I just manually cache what I need because of THEM..lol

**Comment by 123Venom** [comment]
And I didn't find a 2008 flavor of the show.  2017 and 2002.

<img width="912" alt="Taken" src="https://user-images.githubusercontent.com/46383815/162641026-595acf6e-886c-4bff-8212-d46de77e4fe7.PNG">

**Comment by TheGuru276** [comment]
> And I didn't find a 2008 flavor of the show. 2017 and 2002.
> 
> <img alt="Taken" width="912" src="https://user-images.githubusercontent.com/46383815/162641026-595acf6e-886c-4bff-8212-d46de77e4fe7.PNG">

Yes sorry. Typo. I meant 2017 and 2002. I'm so used to having the Kodi addons find everything for me that I forgot I can source them manually and add them to AD. As I ended up doing for Starstruck, but from memory I've been unable to find sources for Taken 2002 so I guess the Kodi addons have little chance as well.

**Comment by 123Venom** [comment]
Did you add the year to the query..lol

![at](https://user-images.githubusercontent.com/46383815/162654182-f702ff09-3921-48e6-97c7-d019c7ac7f7a.png)
