### ISSUE TITLE
Translations de

### ISSUE THREAD

**Issue by bjbca** [123Venom/plugin.video.venom#23]
Ok, here is the first run at German strings.po, it needs to be tested... outa time here for now, there may be some text symbols that need fixing (accents), check it out, let me know,https://github.com/bjbca/redone/blob/master/de.po

**Comment by drinfernoo** [comment]
Why would you do it like this, rather than as a proper Pull Request? If you fork the project, modify the involved files, and then open a PR, they can simply be merged in a single click, rather than needing to download the file, make the necessary changes, etc... You've basically created more work for the developer by submitting your changes in such an unconventional way.

**Comment by bjbca** [comment]
its the entire file from scratch, and no i dont want to carry the fork, and no i dont want any credits... was asked for help and thats my help.... work yeh it was quite a bit of work doing the translation.

**Comment by 123Venom** [comment]
ok..I confess this was a bait and switch thing I did because of an issue he posted over an en.po file that I got a bit bothered by his pettiness and incorrect stating of problems so I'm turning issues off issues from here on out.  Night folks but bout to call this quits cause teh BS complaints getting to much for my taste.
