### ISSUE TITLE
Duplicate Trakt Progress List upon completion

### ISSUE THREAD

**Issue by stathis95194** [123Venom/plugin.video.venom#42]
I have an issue which is random. I usually watch my shows through the Trakt Progress section of My TV Shows. Upon completion of the played video, the list refreshes (as i have Force Container Refresh checked in Playback Settings). Unfortunately upon refresh, most of the time the list is either empty or shows all tv shows as duplicate.
If i go back and reload Progress, all is fine.

![Capture](https://user-images.githubusercontent.com/12883036/76218169-6917df80-621c-11ea-94ba-b250e84d9ed9.PNG)

**Comment by 123Venom** [comment]
Yes I have noticed this and seems to be related to my auto playlist creation after playback ends.  I've just not had a chance to look at it but it is on the old to-do-list.  It refresh proper when you exit and re-enter so I just placed the issue as not a high priority for now...sorry been working on OpenScrapers update for last few weeks but this will be looked at and I'm aware of it.

**Comment by 123Venom** [comment]
Finally got around to doing some testing on this issue.  Seems to me when `Autoplay` is in use and `force container refresh` there's some goofy kodi bug because the behavior is inconsistent.  Sometimes the duplicates will go `01,01,02,02,03,03` and other times it will go `01,02,03,01` etc.  The order changes from one minute to the next.  Sometimes I even end up seeing `00000.B` where the runtime of the episode is listed.  When you enable the `container refresh` option the only thing I do is a call to a kodi function `xbmc.executebuiltin('Container.Refresh')`.  There's no magic in Venom where a bug could be and near as I can tell, from the inconsistent behavior of that kodi function, is this is a kodi bug.  If I disable the option the problem has not occurred once.  I've inquired to a few other devs to see what might be known of this issue for now.

**Comment by 123Venom** [comment]
found a work around for this issue so I'll close this and it will be included in next update for conditions where `container refresh` is enabled.

**Comment by ShaVerZ** [comment]
> Yes I have noticed this and seems to be related to my auto playlist creation after playback ends. I've just not had a chance to look at it but it is on the old to-do-list. It refreshes proper when you exit and re-enter so I just placed the issue as not a high priority for now...sorry been working on OpenScrapers update for last few weeks but this will be looked at and I'm aware of it.

No problem mate. However, I can't get it to update if I exit and re-enter. I've spent the last few days clearing my device and it seems to scan but not add anything new. I've tried other options like Library Updater and I couldnt get any of those to work. I thought I may have been doing something wrong.

As I know you are aware, I'll wait until you have the time. I'm in no rush and understand you are busy, stay safe....
