### ISSUE TITLE
v353 remove dup setting causing hang during some scrapes

### ISSUE THREAD

**Issue by bjbca** [123Venom/plugin.video.venom#43]
v353, during some scrapes the links would appear but the gears would stay spinning, pressing back would stop the hang, nothing shows in the logs.. Ven, Kodi or OS, so it took some time to narrow it down to the new code for remove duplicates, if one simply chooses to let remove duplicates log things still hang but if one chooses to not remove duplicates then the scrape doesn't hang, maybe only happens if the scrape doesn't come up with any dups...

**Comment by 123Venom** [comment]
The remove duplicates was not added in v3.5.3, that was done months ago.  I did add an option to stop logging all the duplicate removed items because it was massively spamming the log.  I think you mean torrent cached/uncached checking which was added in v3.5.3.  Sadly I can't replicate this hang.

**Comment by 123Venom** [comment]
Saw your post over on OpenScrapers.  You might want to dig into that cfScrape issue I commented on as that could be the source of your hang.

**Comment by bjbca** [comment]
👍 thnx

**Comment by bjbca** [comment]
So, i have cleaned up OpenScrapers thank you for that, and running Venom 355.. still having some hanging once a scrape is done, happens less when remove.duplicates is false and remove.duplicates.logging is true, remove.duplicates did work fine before remove.duplicates.logging was implemented, but im not saying that remove.duplicate code is the issue... just it seems to happen less when that setting is not used... i will keep digging, just hard when nothing shows in any of the logs, i will close the issue though.

**Comment by 123Venom** [comment]
the remove duplicates logging that was added in v3.5.5 in no way can have this impact so it's coincidence.  I will say just yesterday a local I setup a Shield for called me over having this very issue.  I stopped over to peak and was doing exactly as you described so my hunch was to clear provider cache because the magnet title option I added won't be there so cache should be cleared to start the links fresh with that magnet title now written.  That cured the issue and it stopped happening...try that.

**Comment by bjbca** [comment]
Yes i have done several rounds of clearing diff caches, prob seems to be randome, but more so with remove dups on, just when i think things are fixed it happens.
I have 2 nvidia shield tv's a 2017 & a 2019, but im testing on a macbook pro, kodi 18.6, estuary skin, have tried disabling various scrapers etc, just using: 
300mbfilms
ddlspot
ganool
maxrls
mkvhub
mvrls
onceddl
onlineseries
projectfreetv
putlockeronl
rlsbb
scenerls
seehd
series9
watchepisodes
watchserieshd
xwatchseries
Other scrapers seem to be problematic in other ways, and the same scraper releases work with Venom 352 and the hang doesnt seem to be there. Also i started using trakt again, and i have a real debrid acct and rd torrents disabled in resolveurl, thats the setup.
 If you are interested, one of the tv searches i do when testing scrapers is, Riviera season 2 episode 1-10 the problem is consistent there, another show i test scrapers with is ray donovan season 6 episode 11.
 This is not a big deal as all one has to do is hit back or right click and the links become active and off you go but this is a strange one so im stuck on figuring out what is causing it.
I will try the latest release 356 and see how it goes. ;)

**Comment by 123Venom** [comment]
So that list is the scrapers you use?  Very unusual setup!!  I do allot of contributions to OpenScrapers, and write most of the torrents it carries,  but I honestly don't touch the free hosters, nor use a single one myself.  I just feel free hosters are a dying breed and a waste of my time.  I don't see a single torrent on that list..how come and why would you disable them?  They're the best sources of links hands down!!  Wait a minute...I chat with allot of ppl daily so excuse me if I forget but are you the one I spoke with once that won't use torrents because of fear of a virus?  If so bud I'll be honest that's the craziest thing I've ever heard and you are missing out on soooo much.  That list of providers there I wouldn't dream of ever using that!  I'm not trying to be rude I'm just beside myself on that list being used by someone who has an RD account...makes no sense at all.  Sorry I'm just trying to help and be openly honest and mean no harm.

Not sure if I've brought this up to you or not but I encourage you to join keybase and if you do I have a Venom chat channel I frequent far more often than here so that might be a good option for you if interested.

I'll try a run of that list but I'm not going to kid you as that list is about the most disgusting set of providers one could use I've seen and won't exhaust to much time on it.

**Comment by bjbca** [comment]
Ok, i will check out some torrent use ;), dont worry about spending time with the scraper list as im pretty sure the scrapers arent the problem because the mild hang started since Venom 353 and before i changed OS versions, and i know you are doing lots of other productive work and i appreciate it. I will look into keybase.

**Comment by 123Venom** [comment]
ok I tried that exact list of yours for Riviera season2 and not a single hang and tried first 3 eps...scenerls was the primary link that kept playing from your list.  I then enabled all default torrents...got 181 links for S02xE01 but yet only 1 `cached` torrent from yourbittorent but it played like a trooper being top of the list to play first before scenerls. S02xE02 again only had 1 cached torrent from torrentz and played fine...must not be a popular show, or gone season packs which Venom does not do at this time.  I can not get it to hang even on your list of providers.  I even then enabled rapidmoviez, with it's known server response time issue causing bogus `Cloudflare_Loop_Protection` and while that error did pop up in my own OS log it still did not cause any hang for me and just times out and moves on.

I'll give you my honest opinion what I think might be happening for you.  Since you had that odd `cfScrape` error yesterday , that only existed had you downloaded tikipete's mod that was never merged, is that you have a scraper hanging around that is mucked or been dropped.  I myself removed a yts torrent that became a mirror site of another and I'm sure tikipete had some as well that were dropped when he did his hoster update.  I suggest at this point a clean install of both Venom and OpenScrapers because I can not reproduce your issue here on latest release using both.  This is absolutely not a dupe removal issue since that was done many months back nor can the logging change I recently did effect this.  Logging for me, with log spamming of dupes turned off, reports just this one line now.

`[2020-03-20 23:37:39] [COLOR red][ Venom DEBUG ][/COLOR]: Removed 156 duplicate sources from list`.  It use to report every item removed and that's what I mean by log spamming, which would not cause a hang either.

**Comment by 123Venom** [comment]
<img width="600" alt="Capture21" src="https://user-images.githubusercontent.com/46383815/77219190-ae37ed80-6b09-11ea-8c70-ecbca4a4f124.PNG">
That cached torrent played in 5 secs in Autoplay mode being it's first...the source list came up in 3 secs in directory mode.  That was with your list and all default torrents enabled.

**Comment by 123Venom** [comment]
https://ufile.io/pb3sutqf not sure it will load but here's a vid I made loading ep3 of that season.  Worked fine if I click the left free link download.  no hang at all and even with that ugly rapidmoviez loaded

**Comment by bjbca** [comment]
Problem solved, Ok because i never used torrents, i would customise OS, it wouldnt have any en_Torrent folder, default.py would not have a torrent section, __init__.py would be edited and settings.xml would only have Hosters and Debrid Only sections, so it seems that when completing a scrape venom expects to sort some torrents but none exist in OS and then a hang, so when i added the torrent folder, settings, init and default sections back, then enabled in resolveurl, cleared venom, os and resolve url caches, then repeated the searches.... all worked as expected ;) so.... i guess i had fuxed it up, and now i use torrents, thank you for all the time you have spent on this seemingly trivial deed :) 💯
