### ISSUE TITLE
Unreleased Movies 

### ISSUE THREAD

**Issue by ShaVerZ** [123Venom/plugin.video.venom#44]
Is there a way of having unreleased movies, title text highlighted red (or choice of colour), It does this for TV Shows/episodes but not for my movies/watchlist.

Thanks for all your hard work, very much appreciated — fantastic add-on!

**Comment by 123Venom** [comment]
In order for something like that we'd need an item in the api response for dvd_release_date.  To my knowledge no api gives this for movies and is why I've not seen this feature you ask for in any addon.  I could be wrong but if you know of one doing this let me know.  The only way to add a feature like that is to access a database that has that info and adding more api requests is not something I wish to do because the more requests we make the slower it becomes.  API's offer a `release_date` but it's for the theatrical release date not dvd.

**Comment by ShaVerZ** [comment]
Seren offers this feature;

![20200322_210825](https://user-images.githubusercontent.com/58187200/77260805-114c9000-6c82-11ea-9b51-7655ff3fd687.jpg)

**Comment by 123Venom** [comment]
I'll check with Nix and see how he's acquiring that info.

**Comment by 123Venom** [comment]
I think perhaps I misunderstood.  I looked at the movie `Greyhound` from you pic and the theatrical release date is not till 6/12/20 and I was thinking you wanted it based on DVD release date...my bad.  That can be done easy enough since we have the theatrical release date.  Surprised you didn't pick up on that

**Comment by ShaVerZ** [comment]
I forgot to mention I was referring to Theatrical release date.

I do have an issue where new episodes seem to be listed late within Next Up section. I've turned off the delay by a day but this still happens.

Westworld S03E02 should be listed within the Next Up section but it is not. I thought I'd check Seren to see if it is displayed within Progress section and it shows up. Am I doing something wrong or missing something? This has been a problem for me for a few months, possibly longer.


Thanks for your support, much appreciated.

**Comment by 123Venom** [comment]
ok where're getting off track and I've already spent 6hrs doing tech support issue and getting a bit burnt out.  Open a new issue on that and i'll look at your Westowrld issue another day.  I did just upload a fix for a possibly related issue to this in the dev branch, test that and see if it also cures your problem.  Two fixes dealing with Trakt Progress in that.  One fixes odd cases where trakt api would place Season0 at the end of your watchlist, when most cases it places it at beginning.  The other was for cases where marking Season0 and the count exceeded the aired episode count reported from trakt, that does not take into account for Season0 so it broke it.

So I'm playing with request your colorization to movies that have not been theater released yet.
<img width="400" alt="MySpy1" src="https://user-images.githubusercontent.com/46383815/77278751-81fda780-6c96-11ea-8496-65ea09477b75.PNG">

Notice MySpy...it's in theaters here but the release date is reported from api as 4/17/2020 and that's wrong!  If I release this you may have little hiccups like that because of incorrect api data.

**Comment by 123Venom** [comment]
hmmm..I'm wondering if movies actually are receiving modified release dates due to the whole coronavirus issue?  That might explain it because local cinemas here are all closed.  The original release date for that title was showing as 3/17/20 and that was not going to happen here.  Couldn't find info on the net searching for it.

**Comment by ShaVerZ** [comment]
A number of movie releases have been brought forward due to COVID—19 https://www.esquire.com/entertainment/g31871914/movies-streaming-early-coronavirus/

The next episode issue isn't a major problem, they just appear 1 day late. I forgot to mention that it happens to all titles and not just Westworld. Perhaps it is a locale issue, I'll check. 

Do not worry about the episode problem, it's not a huge issue.

**Comment by 123Venom** [comment]
ok I'm a bit confused....original release date vs. digital release date for streaming?  I didn't see the title I listed and what I saw was streaming changes?   That's still completely different than theatrical release dates....no?

**Comment by ShaVerZ** [comment]
Here in the UK, those titles were due to Theatrical release but as all the cinemas are on lockdown, they've released them to stream online. If they did not do this, they would have lost alot of money. 

So they were due in the cinema but that was changed so they are now available to stream. Bloody expensive though! It looks like all the major movie studios are now doing this.

**Comment by 123Venom** [comment]
ya I figured right now with this coronavirus it's all a mess.  I went ahead and left it with a new setting option that you can set desired color.

<img width="400" alt="Capture41" src="https://user-images.githubusercontent.com/46383815/77289279-07da1c80-6cb0-11ea-9984-7e322526c956.PNG">

That work?  I know right now release dates prob all over the place and inaccurate.

Hope yall are safe and good!!

**Comment by ShaVerZ** [comment]
Fantastic mate, appreciate it. Hope all is well your end. I'm in a high risk category so I'm now stuck in for 12 weeks and my two teenage lads also - have a prayer for me buddy, I'm sure my lads will get to me before this Coronavirus lol

**Comment by ShaVerZ** [comment]
> ya I figured right now with this coronavirus it's all a mess. I went ahead and left it with a new setting option that you can set desired color.
> 
> <img alt="Capture41" width="400" src="https://user-images.githubusercontent.com/46383815/77289279-07da1c80-6cb0-11ea-9984-7e322526c956.PNG">
> 
> That work? I know right now release dates prob all over the place and inaccurate.
> 
> Hope yall are safe and good!!

This is off-topic but have you any idea what is going on with the YouTube? I created my API keys and it works great with Venom for trailers but as soon as I login/link my google account by signing in, the YT addon ceases to work. I must then go in to the configure settings and remove/delete user and the addon works again but only for trailers.

I'm not after any help, just curious how some seem to get it fully working but others not.

Take care

**Comment by ShaVerZ** [comment]
I got the YouTube addon resolved; for some reason the current version would not allow me to sign in but I managed to find v6.7.0 and this allowed me to link my Google account, using my own API. The version within the Kodi Repo (v6.6.0) would accept my API keys but as soon as I linked/signed in the addon wouldn't work until I removed my user account.

So all seems fine with v6.7.0

Have a good day mate and thanks again.
