### ISSUE TITLE
Global Context - Rescrape Item with Remove HEVC streams causes endless 'working'

### ISSUE THREAD

**Issue by Spooge-DAmour** [123Venom/plugin.video.venom#53]
In the new context menu item Rescrape Item seems to get stuck in an endless loop after the scrape if the Remove HEVC option is selected in the Source Options.  It looks like the scrap happens normally with the scrape dialog appearing, however after it is finished the scrape is goes into an endless 'Working' spinner loop.

Keep up the great work.  It is greatly appreciated.

**Comment by 123Venom** [comment]
see my reply to your other posted issue...same applies here.  Both cases already known and fixed...just buttoning up OpenScrapers update.

**Comment by 123Venom** [comment]
I also just checked the global context option to `Rescrape` with these fixes in place.  No infinite loop takes place...not sure about before but I suspect those issues may have caused it for you.

**Comment by Spooge-DAmour** [comment]
It was a very specific set of option issues. The endless "Working" only happened with a Rescrape Item when the Remove HEVC was enabled, if it wasn't selected the Rescrape Item worked just fine.  I do have all the free, debrid and torrent scrapers enabled.  Yes... I am a source whore.... 

Thanks again sir.

If I got off my ass and took the Python courses I bought I might even be able to throw some help your way.

**Comment by 123Venom** [comment]
Your scrape must be slow using all that...i use 2 feee hosters, no debrid providers, bout 8 torrents only.  Thats all I ever need and scrape is very fast.  The 2 hosters I use are good backups for hard to find episodes.

**Comment by DjAnu** [comment]
Yes scrapping takes at least a couple of min. I have disabled all foreign hosters and have kept everything else default. I do have Real-Debrid Acct. Could you share your hosters and torrents ? I also would like to optimize the source settings to avoid long scrapping time. Also is it possible to add file size filter ?

**Comment by 123Venom** [comment]
I was thinking just yesterday of adding a Venom tool option something like "Venom's preferred Openscraper settings".

Free hosters I use watchepsiodes only for now, was using watchserieshd also but both are a 2-3sec scrape time and I hate slow scrapers.  They're good for shows that can be hard to find and believe it or not they find episodes at times when all 30 torrents fail...that's why I like them

No debrid

Torrents.
7torrents(.78sec), btscene(.86sec), eztv(.96sec), torrentapi(2.48sec), torrentdownloads(.63sec), yourbittorent(1.444sec). Anything that takes beyond 3secs to scrape alone I consider it slow...and yes I timed each and every scraper by itself.
few of those are torrent search engines that search the others so enabling a whole bunch becomes redundant and a waste of scrape time.  That combo works great for me, plus they yield the fastest scrape times.  Slow scrapers in order worst first are isohunt2(10sec), ettv(8sec), 1337x(5sec), torlock(4secs)...rest are all 3secs or less.

I was planning on making a spread sheet of all the scrape times and uploading it when I get time.

**Comment by DjAnu** [comment]
Thank You. Yes having a preferred setting option would be great for some of us newbies. Also if we could files for a size limit that would be awesome. For some of the movies I see at least 30+ searches with file size greater than 40 GB that doesn't play on my 1 gbps network. Probably device limitation than the bandwidth.

**Comment by 123Venom** [comment]
I'll see bout adding a file size limit filter..should be easy enough.

**Comment by DjAnu** [comment]
great, that would be awesome. I can use autoplay then :-).

**Comment by 123Venom** [comment]
> 
> 
> great, that would be awesome. I can use autoplay then :-).

I just finished up a test v3.6.8a and added your requested `FileSize limit`.  You can find it 
[https://github.com/123Venom/zips/tree/dev](here)
It needs further testing as I was short of time and only ran a few scrapes but results looked good.

**Comment by DjAnu** [comment]
Great. Thank you. I'll try and will let you know if I find any issues.
Thanks a lot for your support.
