### ISSUE TITLE
Open-Meta and Venom auto-play

### ISSUE THREAD

**Issue by SoulTV** [123Venom/plugin.video.venom#6]
When using Venom through OpenMeta, the Up Next window pops up and it triggers the next video but you have to manually select Venom from the OpenMeta dialog. Not a big deal, just bringing it to your attention as many people probably use Venom with OpenMeta. 

Btw, awesome addon and thx for all of your work!

**Comment by reddit-reaper** [comment]
this would be more of an issue for OpenMeta

**Comment by drinfernoo** [comment]
I think if Venom implements Up Next correctly, it should continue playing regardless of OpenMeta. This works with OpenMeta -> Seren with Up Next integration, so I would think it would work with Venom as well.

**Comment by SoulTV** [comment]
I would think OM shouldn't play a part in it but Gaia 5's "binge mode" also doesn't work through OM so I'm not sure. I have a ticket open on Gaias website and they say OM is the issue but idk

**Comment by drinfernoo** [comment]
@SoulTV Gaia is even using Up Next, but rather their own implementation, so that's a completely different issue.

**Comment by SoulTV** [comment]
@drinfernoo , I understand Gaia isnt using Up Next. Gaias implementation is called "Binge Mode" which is why I mentioned that in my previous post. Because of the ticket I opened on Gaias website they tried to implement a fix for "Binge Mode" not working through OM. In the changelog for Gaia 5.0.5, you'll see this referenced as "fix problem with external players" or something to that effect. However, the fix does not actually trigger "Binge Mode" it actually triggers Up Next at the end of episodes. So in 5.0.4 Gaia did not use Up Next but in 5.0.5 Gaia is using Up Next, at least when playing using OM. Try it out

**Comment by 123Venom** [comment]
Sorry little late getting here, been swamped.  Anyway I can talk to the OM dev but my hunch says this boils down to the current method I'm implementing playback for UpNext use.  Ideally it should be using a call to the Kodi playlist, which I do create and can be seen via the "Playlist Manager".  However no matter what I tried the call failed.

control.player.play(control.playlist)

It would begin the scrape process but playback would never begin.  I nearly tossed out the whole UpNext integration idea.  I let it release with the idea that using 'Play from Here", or launching playback from within my "Playlist Manager" worked fine so this had to due till I can solve this mystery.  I needed a break from it because I also exhausted nearly 2 days debugging communication drops with UpNext that I finally chose to reach out to the UpNext dev and discovered he was aware of the issues and had a new version not released yet, v 1.0.1 cured all those issues when he sent it to me to test.  So without playback from an actual playlist I tend to doubt OM can do anything about that.  Then there's the fact that my playlist is generated from entering a shows season so the populated list is then written to the Kodi playlist.  I'm not sure OM would even have access to that to pass.  I'll check with OM dev to see how this playlist is being handled with Seren. If Seren is writting that playlist from a simple call from OM I can tell you that would require a complete re-write on my end and one I doubt I'll be to eager to touch anytime soon.  Also odly I can inquire upon this playlist size with...

playlistSize = control.playlist.size()
xbmc.log('playlistSize = %d' % playlistSize, 2)

And it returns the correct number of episodes in the playlist but the call to begin playback fails, drove me nuts and made no sense.  I plan is to revisit this issue soon.

**Comment by 123Venom** [comment]
Just having a quick look at this and seeing "Seren (Smart Play)" that must be Nix's way of building a playlist for UpNext to work from OM.  I can assure you code outside of Venom for playlist builder I do not have and would take some time to do a playlist of that nature to work.

![Capture](https://user-images.githubusercontent.com/46383815/60763548-bff16780-a044-11e9-81e3-19ae74372660.PNG)

**Comment by drinfernoo** [comment]
@123Venom "Smart Play" is indeed Seren's name for its Up Next implementation, and OpenMeta works fine with that because the trigger for it is part of the URI used to play media. OpenMeta sends that as part of it's player URI, and Seren performs with Smart Play on.

**Comment by 123Venom** [comment]
So OM just sends the url and episode info for that one item you chose and Seren's SmartPlay then builds a playlist from that..right?
If the above is right I'd need a whole list builder to work from an external call like that...and that ain't no quick simple task.  Not sure how high a priority I'll put on this but it's been added to my little to-do list, which grows faster than I can tackle it.

**Comment by drinfernoo** [comment]
@123Venom Correct, that's how Seren has always worked 👌
