### ISSUE TITLE
My TV Shows - Progress

### ISSUE THREAD

**Issue by stathis95194** [123Venom/plugin.video.venom#64]
I noticed one issue in My TV Shows - Progress.
When there are 2 unwatched shows, the show name is visible before episode title.
When only 1 unwatched is present, only episode title is visible, show name is missing.
Attached photos, hope they are clear

![IMG_20200613_232916](https://user-images.githubusercontent.com/12883036/84578435-e0d24900-adcd-11ea-8cbe-0e011d801b6e.jpg)
![IMG_20200613_233006](https://user-images.githubusercontent.com/12883036/84578438-e29c0c80-adcd-11ea-96cc-56bd7771094f.jpg)

**Comment by 123Venom** [comment]
I had a brief look at this and see why it's happening.  When the list items are built it checks if the episodes are a multi list, from different shows, or episodes from same show/season.  It needs two items for the check so it's treating a single item like it would a season list of episodes.  I have a solution but it's going to be a pita to implement so I'm not placing a high priority on fixing this.  I've not noticed it because frankly in all my years I don't recall a time only having one item in my Trakt Progress...keep two..lol.

**Comment by stathis95194** [comment]
Well that's a result of COVID19 lockdown. In all my years watching TV Shows I think it's the first time I'm running out of something to watch, hence the issue presented itself. Not a big deal, just thought to mention it. Keep up the good work and most importantly stay safe!!

**Comment by 123Venom** [comment]
It would actually do the same thing in say a Calendar list where it's episodes from different shows but that list is never one item so we don't see it and the two items needed for the check works fine.  Only way to fix that progress list for a single item is I'd have to create a new argument to pass that the list is `progress_list` so the check would then not be needed and I'd just look what type of list is being passed...but it's a pita..lol.  I may address it on a bored day.

**Comment by 123Venom** [comment]
Not sure if you noticed or not but I pushed an update that addressed this one item in your Progress list issue.

**Comment by stathis95194** [comment]
Of course I noticed. Updated Venom just didn't have anything in my Progress to test it with. Just did though and now it's showing the show name even with 1 TV Show. Thanks a lot for that, that's why Venom is the best!!!

**Comment by 123Venom** [comment]
good deal...appreciate it and closing issue
