### ISSUE TITLE
New Setup // Issue with Library

### ISSUE THREAD

**Issue by ShaVerZ** [123Venom/plugin.video.venom#71]
I had to complete a factory reset of my FireTV and I cannot get the Kodi Library to play anything.

I select a title and get the following error;

"playlist: cant find next item to play"

I've checked and checked my settings and all seems fine, I must be missing something.

**Comment by ShaVerZ** [comment]
I decided to rollback the latest update and all seems fine, something within the latest update is causing the earlier issues.

So I've got it up and running.....

**Comment by 123Venom** [comment]
Seems there I go again...forgot all about those damn strm files.  They do not pass meta and that's a huge problem with all the new code of pack files.  I just spent 2hrs coding a good deal over to fix the whole thing but all seems good not.  I'll push the update in a few.
You might find me shutting issues off for a week because I soooo need a break.  I nearly said, `I'll tackle this next week` because I'm junk but it's done.

**Comment by ShaVerZ** [comment]
Sorry for the delay, I just wanted to thank you for all your hard work — very much appreciated.

Go take a break mate, you deserve it 100%! You spend a lot of time on this project and you deserve great credit!

Have a good day and thanks again.

**Comment by 123Venom** [comment]
Thank you!
