### ISSUE TITLE
Venom TV Show Openinfo issue

### ISSUE THREAD

**Issue by bigpoppapaul** [123Venom/plugin.video.venom#73]
Some shows through Venom cannot access openinfo, which on others it works fine. I did a comparison with Seren and they are all fully accessible. 
Wondering if you know why this might be happening. I've connected a video because it's just easier to show. 
It happens whether I search the shows out, or access it through the Trakt manager on venom. 

https://youtu.be/HMXA1FZkPF4

I know openinfo is not really being updated, but just wondered if it was something that was easily fixable. 

edit: actually, standby, I'm seeing if I can go around this issue in openinfo so no need to look into it at the moment. :)

**Comment by 123Venom** [comment]
I'll go over all this and see what I can find.  I seem to recall like 6 months back I had done some changes for similar issues regarding OpenMeta and OpenInfo, some of which I may have even removed the code when the dev went awol and appeared they were both dead and replaced by TMDbHelper so I focused support there.  That's why the OpenMeta player files were so outdated...that addon is dead.  I'll peak at it...the video in background pretty sure I know what causes it and it's an easy fix.  As a quickie solution `tab` will bring the video forward.

 I just spent all day wrapping up code work and testing the RD `Premium Service` tools.  I had Pm done on last update but an issue that got brought to my attention forced me to prematurely push the update out with only PM done.  Now all cloud files for both RD and PM can be managed. 

I also added a new setting option where a user can flip on the kodi 18 option for `<reuselanguageinvoker>false</reuselanguageinvoker> `.  Google it and read about it if you're not familiar with it.  I was amazed at the performance gain and menus loading much faster....comes at a price though.  Apparently there's a thread issue with widgets that can crash kodi.  The issue is posted on their github so who knows if they'll address it or when.  I've run it enabled for 2 days now on 3 devices...one device crashed once while returning to homescreen from a widget.  Took me a bit of code changes to deal with the requirements it has but the ability to use it is there.  If it crashes..well ya got a setting option to flip it off.

And just as I was wrapping up testing to push this update....that freakin show `24` is doing that OpenInfo BS again.  Going to push this update out and just focus on wth is happening there, and look over your new issues.  This time I'm not clearing anything and reviewing the database file to see if anything mucked with that shows data.

**Comment by 123Venom** [comment]
FOUND IT!  both `24` and `Westworld` are back to messing up for me trying to use OpenInfo on them.  The database indicates the damn epsiode title is over-writing the tvshowtitle.  Missing meta at the episode level and my fallback looks to be the cause doing it for a few limited cases I'm seeing.  It's also doing the same with plot.  Instead of the show level plot it's changing it to an episode level plot.  Fixed and running some tests on it now.  Your otther issue I'll get to in the next day or so to see bout fixing that as well.

**Comment by 123Venom** [comment]
Have you noticed that the items messing up in your Trakt Collection happen to also exist in your Trakt progress?  I have 23 items in my Collection and two of them also exist in my Trakt Progress list...guess which two? Trakt progress widget?

**Comment by 123Venom** [comment]
This turned into a major disaster.  While the fix I did it resolved the issue with a few random shows having meta data changed, which was my goof. This change did however display a new problem I can't solve.  I have 3 new shows now not working that I swear did before.
The Twilight Zone
Heartland
Castle
Interestingly enough these 3 shows are the ONLY shows in my list that the `original_title` is different than the `title`.  Take **Heartland** vs. **Heartland (2007) (CA)**, **The Twilight Zone** vs. **The Twilight Zone (2019)**, and **Castle** vs. **Castle (2009)**.  These 3 shows OpenInfo does not work on. I then switched Venom's `tvshowtitle` to use the original_title...in other words I went from **The Twilight Zone (2016)** to **The Twilight Zone** and guess what?  It worked.  This imo is bad practice.  In the case of reboot shows the show should contain the year as most meta providers do provide it that way.  The original_title in this case is really the 1959 show, but without a year in it OpenInfo brings up the 2019 version...if the year is in it OpenInfo fails!  That's not good.  The Twilight Zone actually has 4 reboots but OpenInfo will only load the 2019 version, even did it to me in Seren to...check it.  Same thing with Heartland which has 3 different shows with the same name yet OpenInfo loads the same **Heartland (2016) (CA)** for all of them.  With the year not in the `tvshowtitle` I got the same results as in Seren, just we both getting one show for 3 different shows...lol. 

So I'm not sure what I'm going to do with this issue but imo it's an OpenInfo one and prob lots to do with missing shows from TMDb.  With the dev awol it's not going anywhere for a fix.  I just want to make sure if I switch to using this original_title to cure OpenInfo's misfortune I'm not breaking anything elsewhere in Venom.  Interestingly enough I just searched TMDb for **The Twilight Zone** and the original show and the 3 reboots are all available.  So why OpenInfo won't work with a date in the `tvshowtitle` is beyond me...remove the date and it will work but only bring up one version of shows with a reboot..yuk!

**Comment by 123Venom** [comment]
Here's official data I logged from TVDB api response for those titles.

```
[2020-08-24 02:32:13] [COLOR red][ Venom DEBUG ][/COLOR]: From func name: resources.lib.menus.tvshows.super_info() Line # :1129
                       msg : title = The Twilight Zone (2019) (ENCODED)
[2020-08-24 02:32:13] [COLOR red][ Venom DEBUG ][/COLOR]: From func name: resources.lib.menus.tvshows.super_info() Line # :1129
                       msg : title = Heartland (2007) (CA) (ENCODED)
[2020-08-24 02:32:14] [COLOR red][ Venom DEBUG ][/COLOR]: From func name: resources.lib.menus.tvshows.super_info() Line # :1129
                       msg : title = Castle (2009) (ENCODED)
```
Search TMDb and the year is not used in the title so I can sort of see why OpenInfo was coded as it was since it relies on TMDb...but how you suppose to pull up other year versions/reboots then?  I couldn't get it to work on that in either Seren or Venom

**Comment by bigpoppapaul** [comment]
My man, you have been working away!

> I just spent all day wrapping up code work and testing the RD Premium Service tools. I had Pm done on last update but an issue that got brought to my attention forced me to prematurely push the update out with only PM done. Now all cloud files for both RD and PM can be managed.

I checked it out. I love it. What a great feature, I'm sure to incorporate that in my friends & family build so as to avoid the "it's not working" messages when their RD expires. 
I tested this for you. The RD worked beautifully. The PM had a couple of issues. Namely "Expires" and "Days Remaining." I tried clearing Venom and system cache and exiting Kodi and then trying it again. Same thing. I uploaded screenshots from my PM account and the addon PM info for you to see. 
![PM1](https://user-images.githubusercontent.com/20094991/91034496-1c11a500-e5d3-11ea-9aa0-f2337f557c58.JPG)
![PM2](https://user-images.githubusercontent.com/20094991/91034607-44999f00-e5d3-11ea-867d-4abe8e9c50d5.jpg)

**Comment by bigpoppapaul** [comment]
> I also added a new setting option where a user can flip on the kodi 18 option for <reuselanguageinvoker>false</reuselanguageinvoker> . 

This sounds handy, I want to check it out. Where in the settings is the toggle? 

> Have you noticed that the items messing up in your Trakt Collection happen to also exist in your Trakt progress?

Yep, you're right. 24, American Gods and Westworld are all unfinished in my Trakt progress. That being said, did you find out how to recreate the issue manually? Or did it just happen? I'm still trying. 

> In my two cases that this happened to those items were on my homescreen widget and the data changed matched the episode item. I'm going to upload a test version for this particular fix to dev branch. Give that a day or two test if you will and make sure we're good.

Yes, I also have Trakt Progress as a homescreen widget. I'll check the fix once you upload it to the dev branch. I didn't see it in there just now when I checked.

**Comment by 123Venom** [comment]
That PM account of yours is strange.  I had 3 guys testing that before I released the PM portion of it last week and none of us saw that condition.  Might be because your expiry is much greater than any of ours was and maybe the api responds differently beyond a full year so I'd have to see the response to know how to deal with it.  Now see this is where I really wish you'd just get on keybase.  I also have a Venom chat channel there I frequent far more than here.  I really only want to come here once a week because the time I spent on keybase, plus coding I really rather not also spend a ton of time here to.  I can make you a special premiumize module where it will log your expiry info and you can send back the log data.  Don't worry I won't log any of your personal info but best you review the log data before you send back.

Here's how mine comes out.  It's really all I had to go by for an api response.
[![20.png](https://i.postimg.cc/Yq9pCLL4/20.png)](https://postimg.cc/Dm9VCZgF)

**Comment by 123Venom** [comment]
I just tossed a v4.0.8a version to the zip/dev branch for you to test.  All that version addresses at this time is the OpenInfo problems.  I changed the **tvshowtitle** **infoLabel** to use the **original_title** for the show.  It solves the problems I mentioned in my conclusion but keep in mind I can not cure the issue OpenInfo has dealing with reboot shows.  That problem happens in Seren and Venom and imo it's not those addons fault from what I saw.

Your other issues I'll get to one at a time but got a busy day ahead of me.

**Comment by 123Venom** [comment]
ok...had another 5min since that's all it took me to make a custom premiumize module to log your account api response.  That new file is in same location as mentioned above.  I had to log the full json response as is before any code of mine touches it so I can see what I'm dealing with.  Review it and edit your personal details and send it back.

**Comment by bigpoppapaul** [comment]
> ok...had another 5min since that's all it took me to make a custom premiumize module to log your account api response. That new file is in same location as mentioned above. I had to log the full json response as is before any code of mine touches it so I can see what I'm dealing with. Review it and edit your personal details and send it back.

Sorry, I'm pretty inexperienced.  To be clear, this is the part you want me to edit?
`			accountInfo = self.get_acount_info()
			log_utils.log('accountInfo = %s' % accountInfo, __name__, log_utils.LOGDEBUG)

			expires = datetime.strptime(str(accountInfo['premium_until']), FormatDateTime)
			log_utils.log('expires = %s' % expires, __name__, log_utils.LOGDEBUG)

			days_remaining = (expires - datetime.today()).days
			log_utils.log('days_remaining = %s' % days_remaining, __name__, log_utils.LOGDEBUG)

			expires = expires.strftime('%Y-%m-%d')
			log_utils.log('expires = %s' % expires, __name__, log_utils.LOGDEBUG)
`

**Comment by bigpoppapaul** [comment]
Sorry, I'm pretty inexperienced here, but just to be clear this is what you want me to edit?

`			accountInfo = self.get_acount_info()
			log_utils.log('accountInfo = %s' % accountInfo, __name__, log_utils.LOGDEBUG)

			expires = datetime.strptime(str(accountInfo['premium_until']), FormatDateTime)
			log_utils.log('expires = %s' % expires, __name__, log_utils.LOGDEBUG)

			days_remaining = (expires - datetime.today()).days
			log_utils.log('days_remaining = %s' % days_remaining, __name__, log_utils.LOGDEBUG)

			expires = expires.strftime('%Y-%m-%d')
			log_utils.log('expires = %s' % expires, __name__, log_utils.LOGDEBUG)`

**Comment by 123Venom** [comment]
Sorry..I take it for granted some times people understand what I want them to do.  Don't edit the module file I uploaded....copy that file over to the **plugin.video.venom.resources.lib.modules** folder.  I'd suggest first finding the original file in that folder and rename it say **_bak**.  then copy it over.  Otherwise that file I uploaded will eventually spam the piss out of your venom.log file, that's not harmful just needless to have it keep writing those log entries over and over, because it will.  You can later replace it with the **_bak** version and the logging will stop.  OK once that file is copied over then in Venom settings **Enable Debug**, 2nd category from the bottom. **Logging Location** make sure is set to **Addon Log**, should be the default.  Now go call up your PM account info in Venom and the api response data, and the few calcs I do, will get logged to **venom.log**.  Depending on what device your on the file may reside in a different place...windows for me it's here C:\Users\my_name\AppData\Roaming\Kodi.  Android I forget the full path but it's the temp folder.  Once you find that venom.log file that's the file you edit.  It's going to have your personal data in it returned from the api request....edit it out!!!  email and ID remove it.  Once that's done that is what I need to see so I can see how the expiry is returned.  My hunch is my code works for under 365 days but after that it fails and I may need to adjust it...I just need to see the response data.

**Comment by bigpoppapaul** [comment]
Or, since I'm guessing you don't have the time to explain this to me and I'm a little lost, I can just send you the info you require

**Comment by bigpoppapaul** [comment]
Gotcha. Ok.

**Comment by bigpoppapaul** [comment]
`[2020-08-24 11:16:25] [COLOR red][ Venom DEBUG ][/COLOR]: From func name: resources.lib.modules.premiumize.acount_info_to_dialog() Line # :134
                       msg : accountInfo = {u'status': u'success', u'limit_used': 0.0, u'premium_until': 1649462400, u'customer_id': u'xxx', u'space_used': 65111106525.0}
[2020-08-24 11:16:25] [COLOR red][ Venom DEBUG ][/COLOR]: From func name: resources.lib.modules.premiumize.acount_info_to_dialog() Line # :137
                       msg : expires = 2016-09-04 04:06:00.240000
[2020-08-24 11:16:25] [COLOR red][ Venom DEBUG ][/COLOR]: From func name: resources.lib.modules.premiumize.acount_info_to_dialog() Line # :140
                       msg : days_remaining = -1451
[2020-08-24 11:16:25] [COLOR red][ Venom DEBUG ][/COLOR]: From func name: resources.lib.modules.premiumize.acount_info_to_dialog() Line # :143
                       msg : expires = 2016-09-04`

**Comment by bigpoppapaul** [comment]
[2020-08-24 11:16:25] [COLOR red][ Venom DEBUG ][/COLOR]: From func name: resources.lib.modules.premiumize.acount_info_to_dialog() Line # :134
                       msg : accountInfo = {u'status': u'success', u'limit_used': 0.0, u'premium_until': 1649462400, u'customer_id': u'xxx', u'space_used': 65111106525.0}
[2020-08-24 11:16:25] [COLOR red][ Venom DEBUG ][/COLOR]: From func name: resources.lib.modules.premiumize.acount_info_to_dialog() Line # :137
                       msg : expires = 2016-09-04 04:06:00.240000
[2020-08-24 11:16:25] [COLOR red][ Venom DEBUG ][/COLOR]: From func name: resources.lib.modules.premiumize.acount_info_to_dialog() Line # :140
                       msg : days_remaining = -1451
[2020-08-24 11:16:25] [COLOR red][ Venom DEBUG ][/COLOR]: From func name: resources.lib.modules.premiumize.acount_info_to_dialog() Line # :143
                       msg : expires = 2016-09-04

**Comment by 123Venom** [comment]
> Little lost here. This is why I'm not on keybase, I'm far too new to be with the big boys over there. :)

That's soooo not true and you'd be surprised.  There's some in Venom chat channel that are sharp as can be...but we got a nice set of newbs as well...lol
Plus this should convenience me to and keybase is much quicker for me to deal with than returning here , which I generally only try to come here on the weekends so don't be shocked I vanish for awhile if you won't do keybase.

**Comment by bigpoppapaul** [comment]
> > Little lost here. This is why I'm not on keybase, I'm far too new to be with the big boys over there. :)
> 
> That's soooo not true and you'd be surprised. There's some in Venom chat channel that are sharp as can be...but we got a nice set of newbs as well...lol
> Plus this should convenience me to and keybase is much quicker for me to deal with than returning here , which I generally only try to come here on the weekends so don't be shocked I vanish for awhile if you won't do keybase.

Alright, alright, I definitely didn't want to be inconveniencing you. I'll get on keybase in the next couple days.

**Comment by 123Venom** [comment]
Something is really goofy with the expiry I can't quite put my finger on it.
My expiry is 313 days and decimal BS puts me at July 4, 2021.  Now look in the format response of mine...2 digit year, then day, then month. Rest is hour BS
**premium_until': 2147385600**

Now per your pic you have 592 days remaining.  So from today's date your expiry would be 4/8/2022 yet I can not make heads or tails of your date to match that up.
**premium_until': 1649462400**

I know a PM sales rep...I'm going to inquire to him on that date format and perhaps my understanding of it is wrong.  I'll have to get back to you when i review this with him.

**Comment by 123Venom** [comment]
> Alright, alright, I definitely didn't want to be inconveniencing you. I'll get on keybase in the next couple days.

Ya sorry just a continual discussion of this nature is to much for me to keep stopping and returning here.  Couple exchanges is usually fine on weekends but this is much more than that...plus I think you tossed in 3 other issues I've not even had a chance to peak at that yet.  That bulk keybase!  Sorry

**Comment by bigpoppapaul** [comment]
> I know a PM sales rep...I'm going to inquire to him on that date format and perhaps my understanding of it is wrong. I'll have to get back to you when i review this with him.

Don't even worry about this one for me. I was just testing it out and showed you my results so you'd know there was something odd with it. 

> Ya sorry just a continual discussion of this nature is to much for me to keep stopping and returning here. Couple exchanges is usually fine on weekends but this is much more than that...plus I think you tossed in 3 other issues I've not even had a chance to peak at that yet. That bulk keybase! Sorry

All good. I actually didn't realize I was pulling you away. My bad.

**Comment by 123Venom** [comment]
I got a shout out to him on the matter.  I'll get to the bottom of it.

**Comment by bigpoppapaul** [comment]
Alright, I'm on keybase. :)
