### ISSUE TITLE
Filenames now match source verbatim.

### ISSUE THREAD

**Issue by HO-Driv3r** [123Venom/plugin.video.venom#74]
My issue is no fault of yours.  It would be more of a feature request.  However, is it possible to get a toggle for switching between file naming methods?  I understand the new method was discussed before it was added, and I see the advantages.  However, with a MASSIVE collection of content, the older method made a few things MUCH easier.  I'm happy to keep manually renaming things after I download them... and the new method IS much more informative.  

It's just that some of the software I use "expects" things to be named in a certain way.  It's no biggie at all; and I hadn't planned on doing anything... but it was suggested I reach out to you on Github.  

Love the addon and respect the hours of free time one has to give up for something like this.  You kick ass.

**Comment by 123Venom** [comment]
Your talking about the downloader changes?  Ya I had a major confrontation with that damn ancient exo base code and while it was great for a simple downloader of scraped cached torrents it just didn't come close to working for downloading of torrent files from your cloud accounts.  I went over it a number of times in my head what to do with the damn thing and the pros of re-writing it as I did vastly outweighed making it work as was for cloud files to.  The problem was that when you scrape from the addon the meta data for the movie/episode was available so the original coder just used the meta **title** (**year**) when they constructed the folder and file name.  Sadly this DOESN'T work with cloud files because all that is stored there is the torrent file name to work from.  So what I'm gathering you're asking for with this toggle is a setting to use the old naming method?  Anything is possible if one is willing to code it and that is not as simple as just putting back the old code. Because it would fail for cloud torrents.  I'd have to write a whole new regex crap to parse the torrent file name down to that old format, bring it back for scrape results would be painless.  I'll give this some thought but to be honest with you it probably would not be to soon I'd tackle this, if at all, because that whole PM and RD Premium Service section took me a good 2 weeks so need a break from peaking at that shit again..lol.  I wrote it in my notes and I don't BS people if I'll consider something so I'll let ya know.

**Comment by HO-Deiv3r** [comment]
I appreciate you responding to this.  Yeah, something like an 'old mode' and 'new mode' toggle.  I don't expect anyone to jump on this.  I just figured at best it might be something you'd consider if you got more feedback similar to mine.  Again, I appreciate you getting back.  If it is something you eventually try to implement, you've got my gratitude in advance.  In the meantime, I'll probably build a script to periodically check/change file names.  Not as simple as it sounds; but doable.  Other considerations, too... like something getting added to a library DB and then getting changed afterward.  It'll be a fun project... or a fucking nightmare.  Either way, it'll be informative.  Thanks again, man.

**Comment by 123Venom** [comment]
While I'm pondering this I was thinking about making a setting for **Format options**.  What was the one that effects you the most, or is it both?  The new folder dropping the parenthesis for an underscore, or does the current folder naming style even effect you?  The file name I set I think I know what your issue with that one is that you just need the **title (year)** and no have it using the torrent file name.  I think I'd prefer to just add an option for **File Format** and show drop down options as.... 

Use - title (year)
Use - torrent file name

I'd like to just do the folder format fixed with no option...need parenthesis back?  That's actually a 2second change now..lol

**Comment by 123Venom** [comment]
Honestly the more I think about this the more I'm realizing I'm better off dealing with it now while that downloader module is still fresh in my noodle.  I know how I am and if I wait a month and go back to it I'm apt to forget shit.

**Comment by 123Venom** [comment]
[downloader-1.png](https://postimg.cc/kD7fDWs2)

**Comment by HO-Deiv3r** [comment]
Sorry for the delay.  Yes, the folder name is also an issue and the format that's "expected" by my setup is:

 "Movie Title (YEAR)" 

and the file name format that's "expected" is: 

"Movie Title (YEAR).EXTENSION" 

I'm sorry again about taking so long to get back to you.  Those screenshots look good.  Like I said before, I don't consider this urgent, but I'm sure appreciative of your response.  My setup is atypical... although I'm sure that if I've done it, so have others.  If there's any more info you need from me, please let me know.  Thank you again!

**Comment by HO-Deiv3r** [comment]
On second thought, I don't know that changing the folder naming back would be in the best interest of all.  An option would be cool; but if it got changes back to using parenthesis, that would also mean using spaces in the name, correct?  Or does the new method also use spaces.. and the underscore just replaces the parenthesis?

**Comment by 123Venom** [comment]
I've got it setup so the folder name is back to exactly how it use to be.  The file name will also be back to how it use to be if you chose the first option in the select dialog..see the second pic I posted.  For me I don't care about the folder name as my setup will work either way.  I just preferred the file name to match the torrent name so I knew a little something about what I once downloaded just by looking at it....plus downloading from your cloud account that is all we have available to us to work from is the torrent file full name.  So right now even if you select that first option, and you wish to download a cloud account torrent file, I now have a regex pattern to parse the torrent file name and replicate that file format you want.

I tested a number of files on the new setup and all seemed to be good...had a few tweaks along the way.  Now that doesn't mean one won't surface that the title makes for a problem with my regex pattern.  If that does happen let me know and title so I can investigate it.  I may toss a test version and upload it to my zips/dev branch for you to try.  I'm sort of in the middle of adding AllDebrid support for chache checking and pack file resolving atm so it'll be some time today...I'll let ya know when it's up there.

During testing I discovered something about the whole module I do not like.  I was calling up the download dialog box as if to proceed with a download, just to read the 3 lines of info in there.  Then I would cancel out but I noted the folder is created even upon cancelling.  That kind of bites but I see why it takes place in the code and frankly it would be a major ordeal to change it so that is going to remain.

**Comment by HO-Deiv3r** [comment]
Man, you rock.  So there's a few empty directories.  That's not a big deal at all because Kodi won't add an empty directory to the library.  Just have to occasionally rm those folders.  All this is way more than I expected.  Thank you for taking the time to look into it.  I will try it out as soon as I see it.  I'll keep an eye out for any anomolies, too.  Thank you.

**Comment by 123Venom** [comment]
That folder creation even if you cancel out issue has ALWAYS done that.  It would have to suffer a 3rd re-write to cure that and I'm about spent on hours into this already.  Why on earth the original exo base code was written to create all the folders...then ask you to confirm download is extremely odd to me.

If you want that folder name changed now's the time to speak up. So the old method, that I'm now back to, would create a movie folder name like **Joker (2019)** so yes there's a space and the parenthesis like the old way was.  The new method I did go to, which that code is now gone...lol, was to name that movie folder **Joker_2019**.  My thought was that was a better folder name structure so no spaces or special characters.  That is literally a 5second change of one line so let me know on that.  I really don't want to add yet another setting for the folder format...we should be able to settle on one.

**Comment by HO-Deiv3r** [comment]
If you've re-adopted "Joker (2019)", that's great for me personally.  I have no other requests.  If folder and file naming are both like old, every device I own already plays nice with that.  I can't guarantee someone else won't gripe, but I love it.  Thank you.

**Comment by 123Venom** [comment]
sorry got side tracked today multiple times...trakt had a maintenance day and I swear every user is tweaking out over it like usual and have no clue what's going on so all I've been doing for hours now is fielding BS so now I'm behind.  prob won't be till tomorrow now I get you a test version.  Apparently the trakt maintenance has done something to sorting user lists so for those who's trakt account is back to working I guess the sorted lists are now all over the place in multiple addons.  Not had a chance to peak at that problem.  Some days I have to question my sanity for doing this.

**Comment by 123Venom** [comment]
v4.0.8c is uploaded to zips/dev branch.  Test and let me know how things are.  I'm working on few different projects atm so official release might not be till few days.

**Comment by HO-Deiv3r** [comment]
So far, so good.  Haven't noticed any hiccups yet.

**Comment by HO-Driv3r** [comment]
Multiple downloads now.  All perfect.

**Comment by 123Venom** [comment]
keep an eye on it.  If all you're doing is downloading from the source select you should be fine since the meta is available there to make your desire file format name.  My concern comes in trying to download from a Premium cloud account.  There I had to use a regex pattern to duplicate your desired file format name.  I'll almost guarantee you eventually you'll stumble upon a title that didn't work and contains a character I didn't expect or the torrent name is some goofy crap that makes no sense other than the person that uploaded it...seen it a million times.  Closing this and should have it out with next update.
