### ISSUE TITLE
double lines in source search window

### ISSUE THREAD

**Issue by ShlomiD83** [123Venom/plugin.video.venom#87]
![Screenshot 2021-06-12 111539](https://user-images.githubusercontent.com/17053215/121770034-ab427600-cb6f-11eb-99cf-530146cb50df.png)

Hi,
Tried multiple skins (not a skin issue).
I'm using windows x64 (if that makes a difference).
Please advise.

Thanks!

**Comment by 123Venom** [comment]
Sure looks like a skin issue to me.  I tried both Silvo and Estuary and it does not do that.  Had a fellow user test AuraMod skin and again it does not do that.  Confluence skin your using? Looks like the skin has issue with updating the progress dialog when `\n` is used for a carriage return, new line.  I won't use `[CR]` there due to a recent discovery that it produces a delay in threaded cases and I ended up with empty dialogs on some devices.  What Kodi version?

<img width="664" alt="scrape1" src="https://user-images.githubusercontent.com/46383815/121784975-206c7600-cb85-11eb-9592-5115d883801c.PNG">

<img width="602" alt="scrape2" src="https://user-images.githubusercontent.com/46383815/121784982-25c9c080-cb85-11eb-97ad-5a0579e17aaa.PNG">

**Comment by ShlomiD83** [comment]
![image](https://user-images.githubusercontent.com/17053215/121785815-a825a500-cbc4-11eb-9de4-252f389f6745.png)

I'm using Kodi 18,9 with Xonfluence skin, but i tried both Confluence & Estuary and the same issue.
the same thing happens on my Xiaomi mibox with Kodi 18.9 & Xonfluence skin.

**Comment by 123Venom** [comment]
Duplicated.  Problem is 18.9 progress dialog does not like `/n` but is fine in 19 and similar issue using `[CR]`.  I'll fix this for 18.9 in next release.

**Comment by ShlomiD83** [comment]
> Duplicated. Problem is 18.9 progress dialog does not like `/n` but is fine in 19 and similar issue using `[CR]`. I'll fix this for 18.9 in next release.

thanks.
