### ISSUE TITLE
A quick question please 

### ISSUE THREAD

**Issue by Tarek-Depp** [123Venom/plugin.video.venom#95]
Hello 
First I want to thank you for this great addon.
I want your help regarding source filtering.
Is there any way to filter out 720p  and below resolution sources??
I tried everything but I'm still getting 720p resolution links.
I'm using kodi 18.9 leia and venom 5.19

**Comment by drinfernoo** [comment]
What is 780p? I've never even heard of that.

**Comment by Tarek-Depp** [comment]
I mean 720p sorry

**Comment by 123Venom** [comment]
@drinfernoo you smart ass...lol.  I stumbled upon an actual 576p link and my first reaction was, "da fuck", heard of it but seeing it real as a cached torrent was another thing.  I don't even think Kodi skins properly identify it but I could be wrong.

Back to op's question.
>>I want your help regarding source filtering.
That wording sounds a bit harsh but I get the lingo.  First Venom offers filtering of the lesser desired quality for CAMS and SD.  SD I even have setup that will not get removed unless a verified better source quality exists in the returned results.  Filtering out 720p also?  I'm honestly not sure I have a desire in even offer that.  That source would be on the bottom on the list so I have to ask...why do you care what's down there?  Hit the last 1080p and call it a day, heck I rarely scroll beyond the first few myself.  I could add a **Min.** quality filter but due to sort order just seems sooo pointless in more iterations to remove what the scrapers return that are at the bottom.  I'll consider it.

**Comment by 123Venom** [comment]
Also to add to my previous comment...you're on 18.9 and just to keep you informed that I have officially removed all Leia versions from my belongs and I've mentioned in the last official Venom release that the next release will have a separate Matrix install that I will continue to develop.  The Leia install will be offered yet I will no longer test nor develop it, nor field questions either...sorry if the last seems harsh I'm just trying to cut my free time investment down from what I'll never use myself.
